[project]
name = "barcode_scanner"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "sila2",
    "typer",
    "pyserial",
    "pywin32",
    "opencv-python",
    "numpy",
    "Pillow",
]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["barcode_scanner*"]

[tool.setuptools.package-data]
"barcode_scanner.generated" = [
    "*/*.sila.xml",
    "*/*.proto",
]
