# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.lockcontroller_impl import LockControllerImpl
from .feature_implementations.simulationcontroller_impl import SimulationControllerImpl
from .feature_implementations.webuiprovider_impl import WebUIProviderImpl
from .feature_implementations.xarm6controller_impl import XArm6ControllerImpl
from .generated.lockcontroller import LockControllerFeature
from .generated.simulationcontroller import SimulationControllerFeature
from .generated.webuiprovider import WebUIProviderFeature
from .generated.xarm6controller import XArm6ControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "xArm 6"
        if description is None:
            description = "UFACTORY xArm 6 robotic arm controller (SiLA 2)"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="XArm6",
            server_version="0.1",
            server_vendor_url="https://github.com/keyser",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        # Main feature
        self.xarm6controller = XArm6ControllerImpl(self)
        self.set_feature_implementation(XArm6ControllerFeature, self.xarm6controller)

        # SimulationController support
        self.simulationcontroller = SimulationControllerImpl(self)
        self.set_feature_implementation(SimulationControllerFeature, self.simulationcontroller)

        # WebUIProvider - serves custom HTML UI for this device
        self.webuiprovider = WebUIProviderImpl(self)
        self.set_feature_implementation(WebUIProviderFeature, self.webuiprovider)

        # LockController
        self.set_feature_implementation(LockControllerFeature, LockControllerImpl(self))
