# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.webuiprovider import WebUIProviderBase

if TYPE_CHECKING:
    from ..server import Server


class WebUIProviderImpl(WebUIProviderBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._html_path = Path(__file__).parent.parent / "custom_ui.html"

    def get_CustomUI(self, *, metadata: MetadataDict) -> str:
        return self._html_path.read_text(encoding="utf-8")
