# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import TYPE_CHECKING, Optional

from sila2.server import MetadataDict

from ..generated.xarm6controller import (
    ArmError,
    ClearErrors_Responses,
    CommunicationError,
    Connect_Responses,
    Disconnect_Responses,
    EmergencyStop_Responses,
    GoHome_Responses,
    NotConnected,
    SetGripperPosition_Responses,
    SetPosition_Responses,
    SetRelativePosition_Responses,
    XArm6ControllerBase,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)

_ICON_PATH = Path(__file__).parent.parent / "icon.png"

_DEVICE_DESCRIPTION = """\
# UFACTORY xArm 6 Robotic Arm

## Overview
6-DOF robotic arm controlled via the xArm Python SDK. Supports Cartesian
position control (tool coordinate space), joint control, gripper operation,
and named position management.

## Capabilities
- **Connect/Disconnect**: Connect to arm via IP address
- **SetPosition**: Move to absolute Cartesian position (X, Y, Z, Roll, Pitch, Yaw)
- **SetRelativePosition**: Jog by relative offsets (tool coordinate space)
- **GoHome**: Return all joints to zero position
- **SetGripperPosition**: Control xArm gripper (0=closed, 850=open)
- **EmergencyStop**: Immediately halt all motion
- **ClearErrors**: Reset error state and re-enable motion

## Properties
- **IsConnected**: Connection status
- **CurrentPosition**: JSON with x, y, z, roll, pitch, yaw
- **ArmState**: 1=moving, 2=ready, 3=paused, 4=error
- **ErrorCode**: Current error code (0=none)

## Coordinate System
All positions use the **tool coordinate space**:
- X, Y, Z in millimeters
- Roll, Pitch, Yaw in degrees
"""


class XArm6ControllerImpl(XArm6ControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._simulation_mode: bool = True
        self._arm: Optional[object] = None
        self._connected: bool = False
        self._sim_position = [200.0, 0.0, 200.0, 180.0, 0.0, 0.0]
        self._sim_state = 2  # ready
        self._sim_error = 0
        self._sim_gripper = 850.0

    def _require_connected(self) -> None:
        if not self._connected:
            raise NotConnected()

    def _check_arm_result(self, code: int, operation: str) -> None:
        if code != 0:
            raise ArmError(message=f"{operation} failed with error code {code}")

    # ── Properties ──────────────────────────────────────────────────────

    def get_IsConnected(self, *, metadata: MetadataDict) -> bool:
        return self._connected

    def get_CurrentPosition(self, *, metadata: MetadataDict) -> str:
        if self._simulation_mode or not self._connected:
            pos = self._sim_position
        else:
            code, pos = self._arm.get_position()
            if code != 0:
                pos = [0.0] * 6
        return json.dumps({
            "x": round(pos[0], 2),
            "y": round(pos[1], 2),
            "z": round(pos[2], 2),
            "roll": round(pos[3], 2),
            "pitch": round(pos[4], 2),
            "yaw": round(pos[5], 2),
        })

    def get_ArmState(self, *, metadata: MetadataDict) -> int:
        if self._simulation_mode or not self._connected:
            return self._sim_state
        return self._arm.state

    def get_ErrorCode(self, *, metadata: MetadataDict) -> int:
        if self._simulation_mode or not self._connected:
            return self._sim_error
        return self._arm.error_code

    def get_DisplayIcon(self, *, metadata: MetadataDict) -> bytes:
        if _ICON_PATH.exists():
            return _ICON_PATH.read_bytes()
        return b""

    def get_DeviceDescription(self, *, metadata: MetadataDict) -> str:
        return _DEVICE_DESCRIPTION

    # ── Commands ────────────────────────────────────────────────────────

    def Connect(self, IpAddress: str, *, metadata: MetadataDict) -> Connect_Responses:
        if self._simulation_mode:
            logger.info("[SIM] Connected to xArm at %s", IpAddress)
            self._connected = True
            self._sim_position = [200.0, 0.0, 200.0, 180.0, 0.0, 0.0]
            self._sim_state = 2
            self._sim_error = 0
            return Connect_Responses(FirmwareVersion="SIM-v2.0.0")

        try:
            from xarm.wrapper import XArmAPI
            self._arm = XArmAPI(IpAddress)
            self._arm.motion_enable(enable=True)
            self._arm.set_mode(0)  # position mode
            self._arm.set_state(0)  # ready
            self._connected = True
            version = getattr(self._arm, "version", "unknown")
            logger.info("Connected to xArm at %s (firmware: %s)", IpAddress, version)
            return Connect_Responses(FirmwareVersion=str(version))
        except Exception as e:
            self._connected = False
            raise CommunicationError(message=f"Failed to connect to {IpAddress}: {e}")

    def Disconnect(self, *, metadata: MetadataDict) -> Disconnect_Responses:
        self._require_connected()
        if not self._simulation_mode and self._arm is not None:
            self._arm.disconnect()
        self._arm = None
        self._connected = False
        logger.info("Disconnected from xArm")
        return Disconnect_Responses()

    def SetPosition(
        self,
        X: float,
        Y: float,
        Z: float,
        Roll: float,
        Pitch: float,
        Yaw: float,
        Speed: float,
        Wait: bool,
        *,
        metadata: MetadataDict,
    ) -> SetPosition_Responses:
        self._require_connected()
        if self._simulation_mode:
            logger.info("[SIM] SetPosition(%.1f, %.1f, %.1f, %.1f, %.1f, %.1f) speed=%.1f",
                        X, Y, Z, Roll, Pitch, Yaw, Speed)
            self._sim_position = [X, Y, Z, Roll, Pitch, Yaw]
            return SetPosition_Responses()

        code = self._arm.set_position(
            x=X, y=Y, z=Z, roll=Roll, pitch=Pitch, yaw=Yaw,
            speed=Speed, wait=Wait,
        )
        self._check_arm_result(code, "SetPosition")
        return SetPosition_Responses()

    def SetRelativePosition(
        self,
        DeltaX: float,
        DeltaY: float,
        DeltaZ: float,
        DeltaRoll: float,
        DeltaPitch: float,
        DeltaYaw: float,
        Speed: float,
        *,
        metadata: MetadataDict,
    ) -> SetRelativePosition_Responses:
        self._require_connected()
        if self._simulation_mode:
            logger.info("[SIM] SetRelativePosition(dx=%.1f, dy=%.1f, dz=%.1f, dr=%.1f, dp=%.1f, dw=%.1f)",
                        DeltaX, DeltaY, DeltaZ, DeltaRoll, DeltaPitch, DeltaYaw)
            self._sim_position[0] += DeltaX
            self._sim_position[1] += DeltaY
            self._sim_position[2] += DeltaZ
            self._sim_position[3] += DeltaRoll
            self._sim_position[4] += DeltaPitch
            self._sim_position[5] += DeltaYaw
            return SetRelativePosition_Responses()

        code = self._arm.set_position(
            x=DeltaX, y=DeltaY, z=DeltaZ,
            roll=DeltaRoll, pitch=DeltaPitch, yaw=DeltaYaw,
            speed=Speed, relative=True, wait=True,
        )
        self._check_arm_result(code, "SetRelativePosition")
        return SetRelativePosition_Responses()

    def GoHome(self, *, metadata: MetadataDict) -> GoHome_Responses:
        self._require_connected()
        if self._simulation_mode:
            logger.info("[SIM] GoHome")
            self._sim_position = [200.0, 0.0, 200.0, 180.0, 0.0, 0.0]
            return GoHome_Responses()

        code = self._arm.move_gohome(wait=True)
        self._check_arm_result(code, "GoHome")
        return GoHome_Responses()

    def SetGripperPosition(
        self, Position: float, Speed: float, *, metadata: MetadataDict
    ) -> SetGripperPosition_Responses:
        self._require_connected()
        if self._simulation_mode:
            logger.info("[SIM] SetGripperPosition(%.1f, speed=%.1f)", Position, Speed)
            self._sim_gripper = Position
            return SetGripperPosition_Responses()

        self._arm.set_gripper_enable(True)
        self._arm.set_gripper_speed(Speed)
        code = self._arm.set_gripper_position(Position, wait=True)
        self._check_arm_result(code, "SetGripperPosition")
        return SetGripperPosition_Responses()

    def ClearErrors(self, *, metadata: MetadataDict) -> ClearErrors_Responses:
        self._require_connected()
        if self._simulation_mode:
            logger.info("[SIM] ClearErrors")
            self._sim_error = 0
            self._sim_state = 2
            return ClearErrors_Responses()

        self._arm.clean_error()
        self._arm.clean_warn()
        self._arm.motion_enable(enable=True)
        self._arm.set_mode(0)
        self._arm.set_state(0)
        return ClearErrors_Responses()

    def EmergencyStop(self, *, metadata: MetadataDict) -> EmergencyStop_Responses:
        self._require_connected()
        if self._simulation_mode:
            logger.info("[SIM] EmergencyStop")
            self._sim_state = 4
            return EmergencyStop_Responses()

        self._arm.emergency_stop()
        return EmergencyStop_Responses()
