# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import io
import logging
import math
import random
import time
from datetime import datetime, timedelta, timezone
from typing import TYPE_CHECKING, List

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.platereader import (
    EjectPlate_Responses,
    GetReaderStatus_Responses,
    InsertPlate_Responses,
    InvalidWavelength,
    PlateNotInserted,
    PlateReaderBase,
    RunMeasurement_IntermediateResponses,
    RunMeasurement_Responses,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)

# Simulated hardware specs
SUPPORTED_WAVELENGTHS = [260, 280, 340, 405, 450, 490, 540, 570, 600, 630, 680]

# Plate format -> (rows, columns)
PLATE_LAYOUTS = {
    24: (4, 6),     # A-D, 1-6
    96: (8, 12),    # A-H, 1-12
    384: (16, 24),  # A-P, 1-24
}


def well_id(row: int, col: int) -> str:
    """Convert 0-based row/col to well ID like 'A1', 'B12', etc."""
    return f"{chr(65 + row)}{col + 1}"


class PlateReaderImpl(PlateReaderBase):
    """Simulated microplate reader.

    Demonstrates:
    - Observable command with many intermediate responses (well-by-well)
    - Complex return data (CSV string with full plate results)
    - List property type (SupportedWavelengths)
    - State prerequisite (plate must be inserted)
    - Defined execution errors (PlateNotInserted, InvalidWavelength)
    """

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.RunMeasurement_default_lifetime_of_execution = timedelta(minutes=30)

        self._plate_inserted: bool = False
        self._last_measurement_timestamp: str = ""
        self._is_measuring: bool = False

    def start(self) -> None:
        super().start()
        logger.info("PlateReader started (wavelengths: %s)", SUPPORTED_WAVELENGTHS)

    # ----------------------------------------------------------------
    # Properties
    # ----------------------------------------------------------------

    def get_IsPlateInserted(self, *, metadata: MetadataDict) -> bool:
        return self._plate_inserted

    def get_SupportedWavelengths(self, *, metadata: MetadataDict) -> List[int]:
        return SUPPORTED_WAVELENGTHS

    def get_LastMeasurementTimestamp(self, *, metadata: MetadataDict) -> str:
        return self._last_measurement_timestamp

    # ----------------------------------------------------------------
    # Unobservable Commands
    # ----------------------------------------------------------------

    def GetReaderStatus(self, *, metadata: MetadataDict) -> GetReaderStatus_Responses:
        if self._is_measuring:
            msg = "Measuring..."
        elif self._plate_inserted:
            msg = "Ready (plate inserted)"
        else:
            msg = "Idle (no plate)"
        return GetReaderStatus_Responses(StatusMessage=msg)

    def InsertPlate(self, *, metadata: MetadataDict) -> InsertPlate_Responses:
        self._plate_inserted = True
        logger.info("Plate inserted")
        return InsertPlate_Responses()

    def EjectPlate(self, *, metadata: MetadataDict) -> EjectPlate_Responses:
        if not self._plate_inserted:
            raise PlateNotInserted("No plate to eject.")
        self._plate_inserted = False
        logger.info("Plate ejected")
        return EjectPlate_Responses()

    # ----------------------------------------------------------------
    # Observable Command: RunMeasurement
    # ----------------------------------------------------------------

    def RunMeasurement(
        self,
        Wavelength: int,
        PlateFormat: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[RunMeasurement_IntermediateResponses],
    ) -> RunMeasurement_Responses:
        # Validate prerequisites
        if not self._plate_inserted:
            raise PlateNotInserted("Insert a plate before running a measurement.")

        if Wavelength not in SUPPORTED_WAVELENGTHS:
            raise InvalidWavelength(
                f"Wavelength {Wavelength} nm is not supported. "
                f"Available: {SUPPORTED_WAVELENGTHS}"
            )

        rows, cols = PLATE_LAYOUTS[PlateFormat]
        total_wells = rows * cols

        logger.info("Starting measurement: %d nm, %d-well plate", Wavelength, PlateFormat)
        instance.begin_execution()
        self._is_measuring = True

        # Estimate ~50ms per well
        estimated_time = total_wells * 0.05
        instance.estimated_remaining_time = timedelta(seconds=estimated_time)

        # Build CSV results as we go
        csv = io.StringIO()
        csv.write("WellId,Row,Column,Absorbance\n")

        wells_read = 0
        for row in range(rows):
            for col in range(cols):
                wid = well_id(row, col)

                # Simulate absorbance reading
                # Base value depends on wavelength, with some spatial pattern
                base = 0.1 + (Wavelength - 200) / 2000.0
                # Add a gradient across the plate (simulates a titration)
                gradient = col / max(cols - 1, 1) * 0.8
                # Add random noise
                noise = random.gauss(0, 0.02)
                absorbance = max(0.0, base + gradient + noise)

                csv.write(f"{wid},{chr(65 + row)},{col + 1},{absorbance:.4f}\n")

                # Send intermediate response for this well
                instance.send_intermediate_response(
                    RunMeasurement_IntermediateResponses(
                        WellResult=f"{wid},{absorbance:.4f}"
                    )
                )

                wells_read += 1
                instance.progress = wells_read / total_wells
                remaining = (total_wells - wells_read) * 0.05
                instance.estimated_remaining_time = timedelta(seconds=remaining)

                # Simulate measurement time per well
                time.sleep(0.02)

        self._is_measuring = False
        self._last_measurement_timestamp = datetime.now(tz=timezone.utc).isoformat()

        results_csv = csv.getvalue()
        logger.info("Measurement complete: %d wells read", wells_read)
        return RunMeasurement_Responses(ResultsCsv=results_csv)
