# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.simulationcontroller import (
    SimulationControllerBase,
    StartSimulationMode_Responses,
    StopSimulationMode_Responses,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)


class SimulationControllerImpl(SimulationControllerBase):
    """Controls simulation mode for the Multidrop Combi server."""

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._simulation_mode: bool = True

    def start(self) -> None:
        super().start()
        self.update_SimulationMode(self._simulation_mode)
        logger.info("SimulationController started (simulation_mode=%s)", self._simulation_mode)

    @property
    def simulation_mode(self) -> bool:
        return self._simulation_mode

    def _disconnect_multidrop(self) -> None:
        """Disconnect the Multidrop Combi instrument when switching modes."""
        combi = self.parent_server.multidropcombi
        # Disconnect real transport if connected
        if combi._transport.is_connected:
            try:
                combi._transport.disconnect()
            except Exception:
                pass
        # Reset simulation connection state
        combi._sim_connected = False
        combi._sim_primed = False
        logger.info("Disconnected Multidrop Combi due to simulation mode change")

    def StartSimulationMode(self, *, metadata: MetadataDict) -> StartSimulationMode_Responses:
        logger.info("Entering simulation mode")
        self._disconnect_multidrop()
        self._simulation_mode = True
        self.update_SimulationMode(True)
        self.parent_server.multidropcombi._simulation_mode = True
        self.parent_server.screenstreamer._simulation_mode = True
        self.parent_server.messagingclient._simulation_mode = True
        self.parent_server.camerastreamprovider._simulation_mode = True
        return StartSimulationMode_Responses()

    def StopSimulationMode(self, *, metadata: MetadataDict) -> StopSimulationMode_Responses:
        logger.info("Exiting simulation mode")
        self._disconnect_multidrop()
        self._simulation_mode = False
        self.update_SimulationMode(False)
        self.parent_server.multidropcombi._simulation_mode = False
        self.parent_server.screenstreamer._simulation_mode = False
        self.parent_server.messagingclient._simulation_mode = False
        self.parent_server.camerastreamprovider._simulation_mode = False
        return StopSimulationMode_Responses()
