# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.usermanualprovider import UserManualProviderBase

if TYPE_CHECKING:
    from ..server import Server

log = logging.getLogger(__name__)


class UserManualProviderImpl(UserManualProviderBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._pdf_path = Path(__file__).parent.parent / "user_manual.pdf"
        self._pdf_bytes: bytes | None = None
        self._manual_text: str | None = None

    def _load_pdf(self) -> None:
        """Load PDF bytes and extract text on first access."""
        if self._pdf_bytes is not None:
            return
        pdf_bytes = self._pdf_path.read_bytes()
        # Extract text using PyMuPDF
        try:
            import fitz

            doc = fitz.open(self._pdf_path)
            pages = []
            for i, page in enumerate(doc):
                text = page.get_text().strip()
                if text:
                    pages.append(f"--- Page {i + 1} ---\n{text}")
            doc.close()
            self._manual_text = "\n\n".join(pages)
        except ImportError:
            log.warning("PyMuPDF (fitz) not installed; ManualText will be empty")
            self._manual_text = ""
        except Exception as e:
            log.warning("Failed to extract text from PDF: %s", e)
            self._manual_text = ""
        # Set _pdf_bytes last — it's the guard flag, so _manual_text must be ready first
        self._pdf_bytes = pdf_bytes

    def get_ManualDocument(self, *, metadata: MetadataDict) -> bytes:
        self._load_pdf()
        return self._pdf_bytes  # type: ignore[return-value]

    def get_ManualText(self, *, metadata: MetadataDict) -> str:
        self._load_pdf()
        return self._manual_text  # type: ignore[return-value]
