# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Venus Method Executor device feature implementation
from __future__ import annotations

import json
import logging
import threading
import time
from datetime import timedelta
from pathlib import Path
from typing import TYPE_CHECKING, Union

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.venusmethodexecutor import (
    AbortMethod_Responses,
    ConnectionError as VenusConnectionError,
    GetCurrentRunData_Responses,
    GetDeckLayout_Responses,
    GetDetailedRunData_Responses,
    GetDevices_Responses,
    GetLoadedMethod_Responses,
    GetMethodFiles_Responses,
    GetRunState_Responses,
    GetRuntimeData_Responses,
    GetRuntimeDevices_Responses,
    InvalidState,
    LoadMethod_IntermediateResponses,
    LoadMethod_Responses,
    MethodNotLoaded,
    PauseMethod_Responses,
    ResumeMethod_Responses,
    SetMethodDirectory_Responses,
    StartMethod_IntermediateResponses,
    StartMethod_Responses,
    UnloadMethod_Responses,
    VenusMethodExecutorBase,
)
from ..venus_client import SimulatedVenusClient, VenusClient

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)


class VenusMethodExecutorImpl(VenusMethodExecutorBase):
    """SiLA 2 feature wrapping the Hamilton VENUS Web API."""

    def __init__(self, parent_server: Server, venus_url: str = "http://localhost:51745") -> None:
        super().__init__(parent_server=parent_server)

        self.LoadMethod_default_lifetime_of_execution = timedelta(minutes=30)
        self.StartMethod_default_lifetime_of_execution = timedelta(minutes=60)

        self._venus_url = venus_url
        self._simulation_mode: bool = True
        self._client: Union[VenusClient, SimulatedVenusClient] = SimulatedVenusClient()

        # State tracking
        self._status = "Undefined"
        self._method_loaded = False
        self._loaded_file_path = ""
        self._is_running = False
        self._is_paused = False
        self._abort_requested = False
        self._latest_trace = ""
        self._method_directory = r"C:\Automation\TestMethods"
        self._lock = threading.Lock()

        self._activity_log: list[str] = []
        self._current_progress: float = 0.0
        self._elapsed_str: str = ""
        self._remaining_str: str = ""
        self._venus_reachable: bool = True

    def start(self) -> None:
        super().start()
        # Push initial observable property values
        self.update_RuntimeTrace("")
        self.update_RuntimeStatus(self._status)
        self.update_IsMethodLoaded(False)
        self.update_BaseUrl(self._venus_url)
        self.update_MethodDirectory(self._method_directory)
        self._push_device_status()
        logger.info("VenusMethodExecutor started (simulation_mode=%s)", self._simulation_mode)

    def set_simulation_mode(self, enabled: bool) -> None:
        """Switch between real and simulated Venus client."""
        self._simulation_mode = enabled
        if enabled:
            self._client = SimulatedVenusClient()
            logger.info("Switched to simulated Venus client")
        else:
            self._client = VenusClient(base_url=self._venus_url)
            logger.info("Switched to real Venus client (url=%s)", self._venus_url)

    # ── DeviceStatus Push ──────────────────────────────────────────────

    def _push_device_status(self, activity: str | None = None) -> None:
        """Push a full device status update via the DeviceStatus observable property."""
        if activity:
            ts = time.strftime("%H:%M:%S")
            self._activity_log.append(f"[{ts}] {activity}")
            if len(self._activity_log) > 100:
                self._activity_log = self._activity_log[-100:]

        status = {
            "isMethodLoaded": self._method_loaded,
            "status": self._status,
            "loadedMethod": self._loaded_file_path,
            "isRunning": self._is_running,
            "isPaused": self._is_paused,
            "venusUrl": self._venus_url,
            "venusReachable": self._venus_reachable,
            "methodDirectory": self._method_directory,
            "simulationMode": self._simulation_mode,
            "progress": self._current_progress,
            "elapsed": self._elapsed_str,
            "remaining": self._remaining_str,
            "latestTrace": self._latest_trace,
            "activityLog": self._activity_log[-50:],
        }
        self.update_DeviceStatus(json.dumps(status))

    # ── Helpers ────────────────────────────────────────────────────────

    def _check_connection(self) -> None:
        if not self._simulation_mode and not self._client.is_reachable():
            self._venus_reachable = False
            self._push_device_status()
            raise VenusConnectionError(
                f"Cannot reach Venus Web API at {self._client.base_url}"
            )
        self._venus_reachable = True

    def _check_method_loaded(self) -> None:
        if not self._method_loaded:
            raise MethodNotLoaded("No method is currently loaded. Call LoadMethod first.")

    def _emit_trace(self, message: str) -> None:
        self._latest_trace = message
        self.update_RuntimeTrace(message)

    # ── Properties ────────────────────────────────────────────────────

    def get_ServerLog(self, *, metadata: MetadataDict) -> str:
        log_file = Path(__file__).parent.parent / "logs" / "venus_api.log"
        if not log_file.exists():
            return "(no log file yet)"
        lines = log_file.read_text(encoding="utf-8", errors="replace").splitlines()
        result = "\n".join(lines[-200:])
        max_len = (1 << 21) - 1024
        if len(result) > max_len:
            result = result[-max_len:]
        return result

    def get_DisplayIcon(self, *, metadata: MetadataDict) -> bytes:
        icon_path = Path(__file__).parent.parent / "icon.png"
        return icon_path.read_bytes()

    def get_DeviceDescription(self, *, metadata: MetadataDict) -> str:
        return (
            "Hamilton VENUS — automated liquid handling system controller.\n"
            "\n"
            "Capabilities:\n"
            "- Load and execute VENUS method files (.med) on Hamilton instruments\n"
            "- Real-time progress tracking via SignalR notifications\n"
            "- Pause, resume, and abort running method executions\n"
            "- Query runtime devices (liquid handlers, heater shakers, temperature controllers)\n"
            "- Retrieve deck layouts showing labware positions\n"
            "- Access run history and detailed execution data\n"
            "\n"
            "Typical workflow:\n"
            "1. LoadMethod (file path, simulation flag) — loads a .med method file\n"
            "2. StartMethod — begins execution (observable, reports progress %)\n"
            "3. Monitor progress via intermediate responses or RuntimeTrace property\n"
            "4. PauseMethod / ResumeMethod — pause and resume as needed\n"
            "5. AbortMethod — cancel execution if required\n"
            "6. UnloadMethod — unload when done\n"
            "\n"
            "Query commands:\n"
            "- GetDevices — list registered devices (JSON array, works without loaded method)\n"
            "- GetRuntimeDevices — list runtime devices with numeric IDs (requires loaded method)\n"
            "- GetDeckLayout (DeviceId) — deck layout for a device (JSON, use ID from GetRuntimeDevices)\n"
            "- GetLoadedMethod — file path of the currently loaded method\n"
            "- GetRunState — current VENUS run state as integer enum\n"
            "- GetCurrentRunData — current execution status (JSON)\n"
            "- GetRuntimeData — historical run entries (JSON)\n"
            "- GetDetailedRunData (RunGuid) — detailed info for a specific run (JSON)\n"
            "- GetMethodFiles — list .med method files in the configured directory (JSON array)\n"
            "- SetMethodDirectory (Directory) — change the directory searched by GetMethodFiles\n"
            "\n"
            "Properties (Observable for real-time SSE push):\n"
            "- RuntimeStatus: Undefined | Initialized | Running | Paused | Aborted | Terminated\n"
            "- IsMethodLoaded: whether a method is loaded\n"
            "- BaseUrl: the Venus Web API base URL\n"
            "- MethodDirectory: directory path for method file searches\n"
            "- RuntimeTrace: latest trace message\n"
            "- DeviceStatus: full JSON state for WebUI (SSE-driven)\n"
            "\n"
            "Notes:\n"
            "- Uses Hamilton VENUS Web API v2 (REST + SignalR)\n"
            "- Supports simulation mode for testing without hardware\n"
            "- Method files must exist on the VENUS PC at the specified path"
        )

    # ── Unobservable Commands ─────────────────────────────────────────

    def PauseMethod(self, *, metadata: MetadataDict) -> PauseMethod_Responses:
        self._check_connection()
        self._check_method_loaded()
        if not self._is_running:
            raise InvalidState("Cannot pause: method is not running.")

        self._client.pause_method()
        with self._lock:
            self._is_paused = True
            self._status = "Paused"
        self._emit_trace("Method paused")
        self.update_RuntimeStatus("Paused")
        self._push_device_status("Method paused")
        logger.info("Method paused")
        return PauseMethod_Responses()

    def ResumeMethod(self, *, metadata: MetadataDict) -> ResumeMethod_Responses:
        self._check_connection()
        self._check_method_loaded()
        if not self._is_paused:
            raise InvalidState("Cannot resume: method is not paused.")

        self._client.resume_method()
        with self._lock:
            self._is_paused = False
            self._status = "Running"
        self._emit_trace("Method resumed")
        self.update_RuntimeStatus("Running")
        self._push_device_status("Method resumed")
        logger.info("Method resumed")
        return ResumeMethod_Responses()

    def AbortMethod(self, *, metadata: MetadataDict) -> AbortMethod_Responses:
        self._check_connection()
        self._check_method_loaded()
        if not self._is_running:
            raise InvalidState("Cannot abort: method is not running.")

        self._client.abort_method()
        with self._lock:
            self._abort_requested = True
            self._is_running = False
            self._is_paused = False
            self._status = "Aborted"
            self._current_progress = 0.0
        self._emit_trace("Method aborted")
        self.update_RuntimeStatus("Aborted")
        self._push_device_status("Method aborted")
        logger.info("Method aborted")
        return AbortMethod_Responses()

    def UnloadMethod(self, *, metadata: MetadataDict) -> UnloadMethod_Responses:
        self._check_connection()
        if self._is_running:
            raise InvalidState("Cannot unload while method is running. Abort first.")

        self._client.unload_method()
        with self._lock:
            self._method_loaded = False
            self._loaded_file_path = ""
            self._status = "Undefined"
            self._current_progress = 0.0
        self._emit_trace("Method unloaded")
        self.update_IsMethodLoaded(False)
        self.update_RuntimeStatus("Undefined")
        self._push_device_status("Method unloaded")
        logger.info("Method unloaded")
        return UnloadMethod_Responses()

    def GetDevices(self, *, metadata: MetadataDict) -> GetDevices_Responses:
        self._check_connection()
        result = self._client.get_runtime_devices()
        return GetDevices_Responses(DevicesJson=json.dumps(result, indent=2))

    def GetDeckLayout(self, DeviceId: int, *, metadata: MetadataDict) -> GetDeckLayout_Responses:
        self._check_connection()
        result = self._client.get_deck_layout(DeviceId)
        return GetDeckLayout_Responses(DeckLayoutJson=json.dumps(result, indent=2))

    def GetCurrentRunData(self, *, metadata: MetadataDict) -> GetCurrentRunData_Responses:
        self._check_connection()
        result = self._client.get_current_run_data()
        return GetCurrentRunData_Responses(RunDataJson=json.dumps(result, indent=2))

    def GetRuntimeData(self, *, metadata: MetadataDict) -> GetRuntimeData_Responses:
        self._check_connection()
        result = self._client.get_runtime_data()
        return GetRuntimeData_Responses(RuntimeDataJson=json.dumps(result, indent=2))

    def GetDetailedRunData(self, RunGuid: str, *, metadata: MetadataDict) -> GetDetailedRunData_Responses:
        self._check_connection()
        result = self._client.get_detailed_run_data(RunGuid)
        return GetDetailedRunData_Responses(DetailedRunDataJson=json.dumps(result, indent=2))

    def GetRuntimeDevices(self, *, metadata: MetadataDict) -> GetRuntimeDevices_Responses:
        self._check_connection()
        self._check_method_loaded()
        try:
            result = self._client.get_runtime_devices_with_ids()
        except Exception as e:
            err_msg = str(e)
            logger.warning("GET /devices/runtime failed (%s), falling back to /devices/registered", err_msg)
            try:
                result = self._client.get_runtime_devices()
            except Exception as e2:
                raise VenusConnectionError(
                    f"Failed to get devices: runtime endpoint returned '{err_msg}'; "
                    f"registered endpoint also failed: {e2}"
                ) from e2
        return GetRuntimeDevices_Responses(RuntimeDevicesJson=json.dumps(result, indent=2))

    def GetLoadedMethod(self, *, metadata: MetadataDict) -> GetLoadedMethod_Responses:
        self._check_connection()
        try:
            result = self._client.get_loaded_method()
            path = result if isinstance(result, str) else str(result)
        except Exception:
            path = ""
        if not path:
            path = self._loaded_file_path
        return GetLoadedMethod_Responses(MethodPath=path)

    def GetRunState(self, *, metadata: MetadataDict) -> GetRunState_Responses:
        self._check_connection()
        result = self._client.get_run_state()
        state = result if isinstance(result, int) else int(result)
        return GetRunState_Responses(RunState=state)

    def GetMethodFiles(self, *, metadata: MetadataDict) -> GetMethodFiles_Responses:
        directory = Path(self._method_directory)
        if not directory.is_dir():
            raise InvalidState(
                f"Method directory does not exist: {self._method_directory}"
            )
        med_files = sorted(str(p) for p in directory.rglob("*.med"))
        logger.info("Found %d method files in %s", len(med_files), self._method_directory)
        return GetMethodFiles_Responses(MethodFilesJson=json.dumps(med_files, indent=2))

    def SetMethodDirectory(self, Directory: str, *, metadata: MetadataDict) -> SetMethodDirectory_Responses:
        Directory = Directory.strip('"').strip("'")
        directory = Path(Directory)
        if not directory.is_dir():
            raise InvalidState(f"Directory does not exist: {Directory}")
        self._method_directory = str(directory)
        self.update_MethodDirectory(self._method_directory)
        self._push_device_status(f"Method directory changed to {self._method_directory}")
        logger.info("Method directory set to: %s", self._method_directory)
        return SetMethodDirectory_Responses()

    # ── Observable Commands ───────────────────────────────────────────

    def LoadMethod(
        self,
        FilePath: str,
        Simulation: bool,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[LoadMethod_IntermediateResponses],
    ) -> LoadMethod_Responses:
        self._check_connection()
        if self._method_loaded:
            raise InvalidState("A method is already loaded. Unload it first.")

        FilePath = FilePath.strip('"').strip("'")

        instance.begin_execution()
        logger.info("Loading method: %s (simulation=%s)", FilePath, Simulation)

        self._emit_trace(f"Loading method: {FilePath}")
        self._push_device_status(f"Loading method: {Path(FilePath).name}")
        instance.send_intermediate_response(
            LoadMethod_IntermediateResponses(StatusUpdate="Loading method...")
        )

        try:
            result = self._client.load_method(FilePath, simulation=Simulation)
        except Exception as e:
            raise VenusConnectionError(f"Failed to load method: {e}") from e

        # VENUS loads asynchronously — poll run-state until Initialized (1)
        INITIALIZED = 1
        TERMINAL_STATES = {4, 5, 6}
        if not self._simulation_mode:
            instance.send_intermediate_response(
                LoadMethod_IntermediateResponses(StatusUpdate="Waiting for VENUS to initialize...")
            )
            self._emit_trace("Waiting for VENUS to reach Initialized state...")
            deadline = time.time() + 120
            while time.time() < deadline:
                try:
                    state = self._client.get_run_state()
                    if isinstance(state, int):
                        state_names = {0: "Unknown", 1: "Initialized", 2: "Running",
                                       3: "Paused", 4: "Finished", 5: "Aborted",
                                       6: "Error", 7: "WaitingForInput", 8: "Starting",
                                       9: "Finishing"}
                        state_name = state_names.get(state, f"Unknown({state})")
                        logger.info("VENUS run-state: %s (%d)", state_name, state)
                        self._emit_trace(f"VENUS run-state: {state_name}")
                        if state == INITIALIZED:
                            break
                        if state in TERMINAL_STATES:
                            logger.warning("VENUS entered terminal state %s before Initialized", state_name)
                            break
                except Exception as e:
                    logger.warning("Failed to poll run-state: %s", e)
                time.sleep(2.0)

        with self._lock:
            self._method_loaded = True
            self._loaded_file_path = FilePath
            self._status = "Initialized"
            self._abort_requested = False

        self._emit_trace("Method loaded and initialized")
        self.update_IsMethodLoaded(True)
        self.update_RuntimeStatus("Initialized")
        self._push_device_status(f"Method loaded: {Path(FilePath).name}")
        instance.send_intermediate_response(
            LoadMethod_IntermediateResponses(StatusUpdate="Method initialized")
        )

        logger.info("Method loaded successfully")
        return LoadMethod_Responses(LoadResult=json.dumps(result))

    def StartMethod(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[StartMethod_IntermediateResponses],
    ) -> StartMethod_Responses:
        self._check_connection()
        self._check_method_loaded()
        if self._is_running:
            raise InvalidState("Method is already running.")

        instance.begin_execution()
        logger.info("Starting method execution")

        with self._lock:
            self._is_running = True
            self._is_paused = False
            self._abort_requested = False
            self._status = "Running"
            self._current_progress = 0.0
            self._elapsed_str = ""
            self._remaining_str = ""

        self._emit_trace("Method execution started")
        self.update_RuntimeStatus("Running")
        self._push_device_status("Method execution started")
        self._client.start_method()

        if self._simulation_mode and isinstance(self._client, SimulatedVenusClient):
            def on_progress(progress: float, detail_json: str) -> None:
                instance.progress = progress
                remaining = (1.0 - progress) * 10.0
                instance.estimated_remaining_time = timedelta(seconds=remaining)
                with self._lock:
                    self._current_progress = progress
                    self._elapsed_str = f"{progress * 10:.0f}s"
                    self._remaining_str = f"{remaining:.0f}s"
                self._push_device_status()
                instance.send_intermediate_response(
                    StartMethod_IntermediateResponses(ProgressUpdate=detail_json)
                )

            def on_trace(msg: str) -> None:
                self._emit_trace(msg)

            final_status = self._client.simulate_run(
                progress_callback=on_progress,
                trace_callback=on_trace,
                check_abort=lambda: self._abort_requested,
                check_pause=lambda: self._is_paused,
            )
        else:
            final_status = self._wait_for_completion(instance)

        with self._lock:
            self._is_running = False
            self._status = final_status
            self._current_progress = 0.0

        self._emit_trace(f"Method execution finished: {final_status}")
        self.update_RuntimeStatus(final_status)
        self._push_device_status(f"Execution complete: {final_status}")
        logger.info("Method execution finished: %s", final_status)

        return StartMethod_Responses(FinalStatus=json.dumps({"status": final_status}))

    def _wait_for_completion(
        self,
        instance: ObservableCommandInstanceWithIntermediateResponses[StartMethod_IntermediateResponses],
    ) -> str:
        """Wait for a real Venus method to complete, polling status."""
        timeout = 3600
        start = time.time()

        while time.time() - start < timeout:
            if self._abort_requested:
                return "Aborted"

            try:
                run_data = self._client.get_current_run_data()
                status = run_data.get("status", "Unknown") if isinstance(run_data, dict) else "Unknown"

                if status in ("Terminated", "Aborted", "Error"):
                    return status

                instance.send_intermediate_response(
                    StartMethod_IntermediateResponses(
                        ProgressUpdate=json.dumps({"status": status})
                    )
                )
            except Exception:
                logger.warning("Failed to poll run status")

            time.sleep(2.0)

        return "Timeout"
