# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import json
import logging
import uuid
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.messagingclient import (
    ConfirmMessage_Responses,
    ConnectToMessageServer_Responses,
    DisconnectFromMessageServer_Responses,
    MessageNotFound,
    MessagingClientBase,
    MessagingError,
    NotListening,
)
from ..messaging_transport import MessagingTransport

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)


class MessagingClientImpl(MessagingClientBase):
    """Lab messaging client SiLA 2 feature implementation.

    In simulation mode, simulates WebSocket message listening.
    In real mode, connects to the lab messaging server via WebSocket.
    """

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._transport = MessagingTransport()
        self._simulation_mode: bool = True

        # Simulation state
        self._sim_listening: bool = False
        self._sim_pending: dict[str, dict] = {}

    def get_IsListening(self, *, metadata: MetadataDict) -> bool:
        if self._simulation_mode:
            return self._sim_listening
        return self._transport.is_listening

    def get_PendingMessages(self, *, metadata: MetadataDict) -> str:
        if self._simulation_mode:
            return json.dumps(list(self._sim_pending.values()))
        return json.dumps(self._transport.pending_messages)

    def ConnectToMessageServer(
        self, ServerUrl: str, InstrumentId: str, *, metadata: MetadataDict
    ) -> ConnectToMessageServer_Responses:
        logger.info("ConnectToMessageServer: url=%s, id=%s, simulation=%s",
                     ServerUrl, InstrumentId, self._simulation_mode)

        if self._simulation_mode:
            self._sim_listening = True
            # Add a simulated pending message for demo
            msg_id = str(uuid.uuid4())
            self._sim_pending[msg_id] = {
                "id": msg_id,
                "title": "Load plate onto scanner",
                "body": "Please place the sample plate on the Micronic scanner and press Done.",
                "instrument_id": InstrumentId,
            }
            return ConnectToMessageServer_Responses()

        try:
            self._transport.connect(ServerUrl, InstrumentId)
        except Exception as e:
            raise MessagingError(str(e))
        return ConnectToMessageServer_Responses()

    def DisconnectFromMessageServer(self, *, metadata: MetadataDict) -> DisconnectFromMessageServer_Responses:
        if self._simulation_mode:
            if not self._sim_listening:
                raise NotListening()
            self._sim_listening = False
            self._sim_pending.clear()
            return DisconnectFromMessageServer_Responses()

        if not self._transport.is_listening:
            raise NotListening()
        self._transport.disconnect()
        return DisconnectFromMessageServer_Responses()

    def ConfirmMessage(self, MessageId: str, *, metadata: MetadataDict) -> ConfirmMessage_Responses:
        logger.info("ConfirmMessage: id=%s", MessageId[:8] if len(MessageId) > 8 else MessageId)

        if self._simulation_mode:
            if not self._sim_listening:
                raise NotListening()
            if MessageId not in self._sim_pending:
                raise MessageNotFound(f"Message {MessageId} not found")
            del self._sim_pending[MessageId]
            return ConfirmMessage_Responses()

        if not self._transport.is_listening:
            raise NotListening()
        try:
            self._transport.confirm_message(MessageId)
        except KeyError:
            raise MessageNotFound(f"Message {MessageId} not found")
        except RuntimeError as e:
            raise MessagingError(str(e))
        return ConfirmMessage_Responses()
