# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import json
import logging
import random
import time
from datetime import timedelta
from pathlib import Path
from typing import TYPE_CHECKING, List

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.micronictubescanner import (
    CommunicationError,
    Connect_Responses,
    DeviceBusy,
    Disconnect_Responses,
    GetScanResult_Responses,
    GetScanResultCsv_Responses,
    MicronicTubeScannerBase,
    NotConnected,
    RescanTube_Responses,
    RetryDecode_Responses,
    ScanBox_IntermediateResponses,
    ScanBox_Responses,
    ScanError,
    ScanTube_Responses,
    SetLayout_Responses,
)
from ..rest_transport import MicronicTransport

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)

# Simulated layouts and barcodes
_SIM_LAYOUTS = ["96-Well Standard", "48-Well Standard", "24-Well Standard"]
_SIM_BARCODE_CHARS = "0123456789ABCDEF"


def _random_barcode() -> str:
    return "".join(random.choices(_SIM_BARCODE_CHARS, k=10))


class MicronicTubeScannerImpl(MicronicTubeScannerBase):
    """Micronic 2D tube-rack barcode scanner SiLA 2 feature implementation.

    In simulation mode, all commands return simulated data.
    In real mode, commands are forwarded to the Micronic REST API.
    """

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.ScanBox_default_lifetime_of_execution = timedelta(minutes=5)

        self._transport = MicronicTransport()
        self._simulation_mode: bool = True

        # Simulation state
        self._sim_connected: bool = False
        self._sim_state: str = "idle"
        self._sim_current_layout: str = ""
        self._sim_layouts: List[str] = []
        self._sim_last_result: str = ""
        self._sim_rack_id: str = ""

    def _require_connected(self) -> None:
        if self._simulation_mode:
            if not self._sim_connected:
                raise NotConnected()
        else:
            if not self._transport.is_connected:
                raise NotConnected()

    # ── Standard Properties ──

    def get_DisplayIcon(self, *, metadata: MetadataDict) -> bytes:
        icon_path = Path(__file__).parent.parent / "icon.png"
        return icon_path.read_bytes()

    def get_DeviceDescription(self, *, metadata: MetadataDict) -> str:
        return (
            "Micronic 2D Tube-Rack Barcode Scanner — reads 2D barcodes on tube bottoms.\n"
            "\n"
            "Capabilities:\n"
            "- Full rack scanning (up to 96 tubes at once)\n"
            "- Single tube scanning\n"
            "- Multiple rack layout support (96, 48, 24 well formats)\n"
            "- Decode retry with adjustable Brightness, Contrast, Threshold\n"
            "- Rack ID reading from barcode on rack\n"
            "- Results in JSON or CSV format\n"
            "\n"
            "Additional features:\n"
            "- Screen streaming (ScreenStreamer): capture application windows\n"
            "- Lab messaging (MessagingClient): receive and confirm operator instructions\n"
            "\n"
            "Typical workflow:\n"
            "1. Connect (base URL) - establish connection to scanner API\n"
            "2. SetLayout - select the rack format if needed\n"
            "3. ScanBox - scan entire rack (observable, polls until complete)\n"
            "4. GetScanResult or GetScanResultCsv - retrieve decoded barcodes\n"
            "5. RetryDecode / RescanTube - fix failed reads with adjusted parameters\n"
            "\n"
            "Commands:\n"
            "- Connect: Set base URL and verify scanner connectivity\n"
            "- Disconnect: Clear the connection\n"
            "- SetLayout: Change the active rack layout\n"
            "- ScanBox: Full rack scan (observable with progress)\n"
            "- ScanTube: Single tube scan\n"
            "- GetScanResult: Get last scan results (JSON)\n"
            "- GetScanResultCsv: Get last scan results (CSV)\n"
            "- RetryDecode: Retry decode with new image parameters\n"
            "- RescanTube: Rescan a tube with new image parameters\n"
            "\n"
            "Properties:\n"
            "- IsConnected: Whether the scanner API is reachable\n"
            "- State: Current scanner state (idle/scanning/dataready)\n"
            "- CurrentLayout: Active rack layout name\n"
            "- AvailableLayouts: List of supported layouts\n"
            "- RackId: Barcode on the rack itself\n"
            "\n"
            "Notes:\n"
            "- REST API runs on port 2500 of the scanner PC\n"
            "- PUT requests require Content-Length header (handled automatically)\n"
            "- States: idle (ready), scanning (in progress), dataready (results available)"
        )

    # ── Device-Specific Properties ──

    def get_IsConnected(self, *, metadata: MetadataDict) -> bool:
        if self._simulation_mode:
            return self._sim_connected
        return self._transport.is_connected

    def get_State(self, *, metadata: MetadataDict) -> str:
        if self._simulation_mode:
            return self._sim_state
        try:
            return self._transport.get_state()
        except Exception as e:
            raise CommunicationError(str(e))

    def get_CurrentLayout(self, *, metadata: MetadataDict) -> str:
        if self._simulation_mode:
            return self._sim_current_layout
        try:
            return self._transport.get_current_layout()
        except Exception as e:
            raise CommunicationError(str(e))

    def get_AvailableLayouts(self, *, metadata: MetadataDict) -> List[str]:
        if self._simulation_mode:
            return self._sim_layouts
        try:
            return self._transport.get_layout_list()
        except Exception as e:
            raise CommunicationError(str(e))

    def get_RackId(self, *, metadata: MetadataDict) -> str:
        if self._simulation_mode:
            return self._sim_rack_id
        try:
            return self._transport.get_rack_id()
        except Exception as e:
            raise CommunicationError(str(e))

    # ── Unobservable Commands ──

    def Connect(self, BaseUrl: str, *, metadata: MetadataDict) -> Connect_Responses:
        logger.info("Connect: url=%s, simulation=%s", BaseUrl, self._simulation_mode)

        if self._simulation_mode:
            self._sim_connected = True
            self._sim_state = "idle"
            self._sim_current_layout = _SIM_LAYOUTS[0]
            self._sim_layouts = list(_SIM_LAYOUTS)
            self._sim_rack_id = f"RACK-{random.randint(1000, 9999)}"
            self._sim_last_result = ""
            return Connect_Responses()

        try:
            self._transport.connect(BaseUrl)
        except ConnectionError as e:
            raise CommunicationError(str(e))
        return Connect_Responses()

    def Disconnect(self, *, metadata: MetadataDict) -> Disconnect_Responses:
        self._require_connected()
        logger.info("Disconnect")

        if self._simulation_mode:
            self._sim_connected = False
            self._sim_state = "idle"
            self._sim_layouts = []
            return Disconnect_Responses()

        self._transport.disconnect()
        return Disconnect_Responses()

    def SetLayout(self, LayoutName: str, *, metadata: MetadataDict) -> SetLayout_Responses:
        self._require_connected()
        logger.info("SetLayout: %s", LayoutName)

        if self._simulation_mode:
            self._sim_current_layout = LayoutName
            return SetLayout_Responses()

        try:
            self._transport.set_current_layout(LayoutName)
        except Exception as e:
            raise CommunicationError(str(e))
        return SetLayout_Responses()

    def ScanTube(self, *, metadata: MetadataDict) -> ScanTube_Responses:
        self._require_connected()
        logger.info("ScanTube")

        if self._simulation_mode:
            time.sleep(0.3)
            barcode = _random_barcode()
            result = json.dumps({"position": "A1", "barcode": barcode, "status": "OK"})
            self._sim_last_result = result
            self._sim_state = "dataready"
            return ScanTube_Responses(ScanResult=result)

        try:
            state = self._transport.get_state()
            if state == "scanning":
                raise DeviceBusy("Scanner is currently busy")
            self._transport.scan_tube()
            self._transport.wait_for_scan_complete()
            result = self._transport.get_scan_result()
        except ConnectionError as e:
            raise CommunicationError(str(e))
        except TimeoutError as e:
            raise ScanError(str(e))
        except Exception as e:
            raise CommunicationError(str(e))
        return ScanTube_Responses(ScanResult=result)

    def GetScanResult(self, *, metadata: MetadataDict) -> GetScanResult_Responses:
        self._require_connected()

        if self._simulation_mode:
            return GetScanResult_Responses(ScanResult=self._sim_last_result)

        try:
            result = self._transport.get_scan_result()
        except Exception as e:
            raise CommunicationError(str(e))
        return GetScanResult_Responses(ScanResult=result)

    def GetScanResultCsv(self, *, metadata: MetadataDict) -> GetScanResultCsv_Responses:
        self._require_connected()

        if self._simulation_mode:
            return GetScanResultCsv_Responses(CsvData="Position,Barcode,Status\nA1,SIM12345,OK\n")

        try:
            csv_data = self._transport.get_scan_result_csv()
        except Exception as e:
            raise CommunicationError(str(e))
        return GetScanResultCsv_Responses(CsvData=csv_data)

    def RetryDecode(
        self, Position: str, Brightness: int, Contrast: int, Threshold: int, *, metadata: MetadataDict
    ) -> RetryDecode_Responses:
        self._require_connected()
        logger.info("RetryDecode: pos=%s, B=%d, C=%d, T=%d", Position, Brightness, Contrast, Threshold)

        if self._simulation_mode:
            time.sleep(0.2)
            return RetryDecode_Responses()

        try:
            self._transport.retry_decode(Position, Brightness, Contrast, Threshold)
        except Exception as e:
            raise CommunicationError(str(e))
        return RetryDecode_Responses()

    def RescanTube(
        self, Position: str, Brightness: int, Contrast: int, Threshold: int, *, metadata: MetadataDict
    ) -> RescanTube_Responses:
        self._require_connected()
        logger.info("RescanTube: pos=%s, B=%d, C=%d, T=%d", Position, Brightness, Contrast, Threshold)

        if self._simulation_mode:
            time.sleep(0.3)
            return RescanTube_Responses()

        try:
            self._transport.rescan_tube(Position, Brightness, Contrast, Threshold)
        except Exception as e:
            raise CommunicationError(str(e))
        return RescanTube_Responses()

    # ── Observable Commands ──

    def ScanBox(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[ScanBox_IntermediateResponses],
    ) -> ScanBox_Responses:
        self._require_connected()
        logger.info("ScanBox")

        instance.begin_execution()
        instance.estimated_remaining_time = timedelta(seconds=30)
        instance.lifetime_of_execution = timedelta(minutes=5)

        if self._simulation_mode:
            return self._scan_box_simulated(instance)

        return self._scan_box_real(instance)

    def _scan_box_simulated(
        self,
        instance: ObservableCommandInstanceWithIntermediateResponses[ScanBox_IntermediateResponses],
    ) -> ScanBox_Responses:
        """Simulate a full rack scan with progress updates."""
        self._sim_state = "scanning"
        total_tubes = 96
        results = []

        for i in range(total_tubes):
            row = chr(ord('A') + i // 12)
            col = (i % 12) + 1
            position = f"{row}{col}"
            barcode = _random_barcode()
            results.append({"position": position, "barcode": barcode, "status": "OK"})

            progress = (i + 1) / total_tubes
            instance.progress = progress
            instance.estimated_remaining_time = timedelta(seconds=(total_tubes - i - 1) * 0.05)
            instance.send_intermediate_response(
                ScanBox_IntermediateResponses(
                    ProgressInfo=f"Scanned {position} - {int(progress * 100)}%"
                )
            )
            time.sleep(0.05)

        result_json = json.dumps(results)
        self._sim_last_result = result_json
        self._sim_state = "dataready"

        return ScanBox_Responses(ScanResult=result_json)

    def _scan_box_real(
        self,
        instance: ObservableCommandInstanceWithIntermediateResponses[ScanBox_IntermediateResponses],
    ) -> ScanBox_Responses:
        """Execute real rack scan via REST API, polling state for completion."""
        try:
            state = self._transport.get_state()
            if state == "scanning":
                raise DeviceBusy("Scanner is currently busy")

            self._transport.scan_box()

            instance.send_intermediate_response(
                ScanBox_IntermediateResponses(ProgressInfo="Scan initiated, waiting for completion...")
            )

            while True:
                time.sleep(0.5)
                state = self._transport.get_state()

                if state == "dataready":
                    instance.progress = 1.0
                    instance.send_intermediate_response(
                        ScanBox_IntermediateResponses(ProgressInfo="Scan complete, reading results...")
                    )
                    break
                elif state == "scanning":
                    instance.send_intermediate_response(
                        ScanBox_IntermediateResponses(ProgressInfo="Scanning...")
                    )
                elif state == "idle":
                    raise ScanError("Scanner returned to idle without producing results")

            result = self._transport.get_scan_result()
        except (DeviceBusy, ScanError):
            raise
        except ConnectionError as e:
            raise CommunicationError(str(e))
        except TimeoutError as e:
            raise ScanError(str(e))
        except Exception as e:
            raise CommunicationError(str(e))

        return ScanBox_Responses(ScanResult=result)
