# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.lockcontroller_impl import LockControllerImpl
from .feature_implementations.camerastreamprovider_impl import CameraStreamProviderImpl
from .feature_implementations.messagingclient_impl import MessagingClientImpl
from .feature_implementations.multidropcombi_impl import MultidropCombiImpl
from .feature_implementations.screenstreamer_impl import ScreenStreamerImpl
from .feature_implementations.simulationcontroller_impl import SimulationControllerImpl
from .feature_implementations.usermanualprovider_impl import UserManualProviderImpl
from .feature_implementations.webuiprovider_impl import WebUIProviderImpl
from .generated.lockcontroller import LockControllerFeature
from .generated.camerastreamprovider import CameraStreamProviderFeature
from .generated.messagingclient import MessagingClientFeature
from .generated.multidropcombi import MultidropCombiFeature
from .generated.screenstreamer import ScreenStreamerFeature
from .generated.simulationcontroller import SimulationControllerFeature
from .generated.usermanualprovider import UserManualProviderFeature
from .generated.webuiprovider import WebUIProviderFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "Multidrop Combi"
        if description is None:
            description = "Thermo Scientific Multidrop Combi reagent dispenser (SiLA 2)"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="MultidropCombi",
            server_version="0.2",
            server_vendor_url="https://github.com/keyser",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        # Main feature
        self.multidropcombi = MultidropCombiImpl(self)
        self.set_feature_implementation(MultidropCombiFeature, self.multidropcombi)

        # ScreenStreamer support
        self.screenstreamer = ScreenStreamerImpl(self)
        self.set_feature_implementation(ScreenStreamerFeature, self.screenstreamer)

        # MessagingClient support
        self.messagingclient = MessagingClientImpl(self)
        self.set_feature_implementation(MessagingClientFeature, self.messagingclient)

        # SimulationController support
        self.simulationcontroller = SimulationControllerImpl(self)
        self.set_feature_implementation(SimulationControllerFeature, self.simulationcontroller)

        # WebUIProvider - serves custom HTML UI for this device
        self.webuiprovider = WebUIProviderImpl(self)
        self.set_feature_implementation(WebUIProviderFeature, self.webuiprovider)

        # UserManualProvider - serves device manual PDF + extracted text for LLM
        self.usermanualprovider = UserManualProviderImpl(self)
        self.set_feature_implementation(UserManualProviderFeature, self.usermanualprovider)

        # LockController - device locking
        self.set_feature_implementation(LockControllerFeature, LockControllerImpl(self))
        # CameraStreamProvider - live camera feed from IP/USB cameras
        self.camerastreamprovider = CameraStreamProviderImpl(self)
        self.set_feature_implementation(CameraStreamProviderFeature, self.camerastreamprovider)
