# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import logging
import threading
import time
from datetime import timedelta
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.pumpcontroller import (
    Dispense_IntermediateResponses,
    Dispense_Responses,
    GetPumpStatus_Responses,
    OverPressure,
    Prime_Responses,
    PumpControllerBase,
    PumpNotPrimed,
    ResetPump_Responses,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)

MAX_FLOW_RATE = 10.0  # mL/s


class PumpControllerImpl(PumpControllerBase):
    """Simulated pump controller.

    Demonstrates:
    - Prerequisite pattern (must Prime before Dispense)
    - Observable command with volume-based progress tracking
    - State management (total dispensed, primed status)
    - Defined execution errors (PumpNotPrimed, OverPressure)
    """

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.Dispense_default_lifetime_of_execution = timedelta(minutes=10)

        self._is_primed: bool = False
        self._total_dispensed: float = 0.0
        self._is_dispensing: bool = False
        self._lock = threading.Lock()
        self._inject_overpressure: bool = False

    def start(self) -> None:
        super().start()
        logger.info("PumpController started")

    # ----------------------------------------------------------------
    # Properties
    # ----------------------------------------------------------------

    def get_TotalVolumeDispensed(self, *, metadata: MetadataDict) -> float:
        return self._total_dispensed

    def get_IsPrimed(self, *, metadata: MetadataDict) -> bool:
        return self._is_primed

    def get_MaxFlowRate(self, *, metadata: MetadataDict) -> float:
        return MAX_FLOW_RATE

    # ----------------------------------------------------------------
    # Unobservable Commands
    # ----------------------------------------------------------------

    def Prime(self, *, metadata: MetadataDict) -> Prime_Responses:
        logger.info("Priming pump...")
        time.sleep(0.5)  # Simulate priming time
        self._is_primed = True
        logger.info("Pump primed successfully")
        return Prime_Responses(PrimeSuccessful=True)

    def GetPumpStatus(self, *, metadata: MetadataDict) -> GetPumpStatus_Responses:
        with self._lock:
            if self._is_dispensing:
                msg = f"Dispensing (total so far: {self._total_dispensed:.1f} mL)"
            elif not self._is_primed:
                msg = f"Not primed. Total dispensed: {self._total_dispensed:.1f} mL"
            else:
                msg = f"Ready. Total dispensed: {self._total_dispensed:.1f} mL"
        return GetPumpStatus_Responses(StatusMessage=msg)

    def ResetPump(self, *, metadata: MetadataDict) -> ResetPump_Responses:
        with self._lock:
            self._is_primed = False
            self._total_dispensed = 0.0
            self._inject_overpressure = False
        logger.info("Pump reset")
        return ResetPump_Responses()

    # ----------------------------------------------------------------
    # Observable Command: Dispense
    # ----------------------------------------------------------------

    def Dispense(
        self,
        Volume: float,
        FlowRate: float,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[Dispense_IntermediateResponses],
    ) -> Dispense_Responses:
        if not self._is_primed:
            raise PumpNotPrimed("Pump must be primed before dispensing. Call Prime first.")

        logger.info("Dispensing %.1f mL at %.1f mL/s", Volume, FlowRate)
        instance.begin_execution()

        with self._lock:
            self._is_dispensing = True

        estimated_time = Volume / FlowRate
        instance.estimated_remaining_time = timedelta(seconds=estimated_time)

        UPDATE_INTERVAL = 0.5
        dispensed = 0.0
        volume_per_step = FlowRate * UPDATE_INTERVAL

        while dispensed < Volume:
            if self._inject_overpressure:
                self._inject_overpressure = False
                with self._lock:
                    self._is_dispensing = False
                raise OverPressure(
                    f"Over-pressure detected at {dispensed:.1f} mL dispensed. "
                    "Check for blockage in the line."
                )

            step = min(volume_per_step, Volume - dispensed)
            dispensed += step

            with self._lock:
                self._total_dispensed += step

            progress = min(1.0, dispensed / Volume)
            instance.progress = progress
            remaining = (Volume - dispensed) / FlowRate if FlowRate > 0 else 0
            instance.estimated_remaining_time = timedelta(seconds=remaining)

            instance.send_intermediate_response(
                Dispense_IntermediateResponses(VolumeDispensedSoFar=dispensed)
            )

            if dispensed >= Volume:
                break

            time.sleep(UPDATE_INTERVAL)

        with self._lock:
            self._is_dispensing = False

        logger.info("Dispense complete: %.2f mL", dispensed)
        return Dispense_Responses(ActualVolumeDispensed=dispensed)
