# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.lockcontroller_impl import LockControllerImpl
from .feature_implementations.messagingclient_impl import MessagingClientImpl
from .feature_implementations.screenstreamer_impl import ScreenStreamerImpl
from .feature_implementations.simulationcontroller_impl import SimulationControllerImpl
from .feature_implementations.venusmethodexecutor_impl import VenusMethodExecutorImpl
from .generated.lockcontroller import LockControllerFeature
from .generated.messagingclient import MessagingClientFeature
from .generated.screenstreamer import ScreenStreamerFeature
from .generated.simulationcontroller import SimulationControllerFeature
from .generated.venusmethodexecutor import VenusMethodExecutorFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
        simulation: bool = False,
        venus_url: str = "http://localhost:51745",
    ):
        if name is None:
            name = "Venus API"
        if description is None:
            description = "Hamilton VENUS Web API wrapper (SiLA 2)"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="VenusAPI",
            server_version="0.2",
            server_vendor_url="https://github.com/keyser",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        # Main feature
        self.venusmethodexecutor = VenusMethodExecutorImpl(self, venus_url=venus_url)
        self.set_feature_implementation(VenusMethodExecutorFeature, self.venusmethodexecutor)

        # Screen streamer
        self.screenstreamer = ScreenStreamerImpl(self)
        self.set_feature_implementation(ScreenStreamerFeature, self.screenstreamer)

        # Messaging client
        self.messagingclient = MessagingClientImpl(self)
        self.set_feature_implementation(MessagingClientFeature, self.messagingclient)

        # LockController support
        self.set_feature_implementation(LockControllerFeature, LockControllerImpl(self))

        # SimulationController support
        self.simulationcontroller = SimulationControllerImpl(self)
        self.set_feature_implementation(SimulationControllerFeature, self.simulationcontroller)

        # Apply initial mode — default is real mode (simulation=False)
        if simulation:
            self.simulationcontroller._simulation_mode = True
        else:
            self.venusmethodexecutor.set_simulation_mode(False)
            self.simulationcontroller._simulation_mode = False
            self.screenstreamer._simulation_mode = False
            self.messagingclient._simulation_mode = False
