# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import logging
import random
import string
import threading
import time
from pathlib import Path
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.barcodescanner import (
    BarcodeScannerBase,
    CommunicationError,
    Connect_Responses,
    Disconnect_Responses,
    InvalidCommand,
    NotConnected,
    Scan_Responses,
    ScanTimeout,
    StopScanning_Responses,
)
from ..serial_transport import DatalogicSerialTransport

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)


class BarcodeScannerImpl(BarcodeScannerBase):
    """Datalogic barcode scanner SiLA 2 feature implementation.

    In simulation mode, all commands are simulated without serial communication.
    In real mode, commands are forwarded to the scanner via serial transport.
    """

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        self._transport = DatalogicSerialTransport()
        self._simulation_mode: bool = True
        self._lock = threading.Lock()

        # Simulation state
        self._sim_connected: bool = False

    def _require_connected(self) -> None:
        """Raise NotConnected if scanner is not connected."""
        if self._simulation_mode:
            if not self._sim_connected:
                raise NotConnected()
        else:
            if not self._transport.is_connected:
                raise NotConnected()

    # ----------------------------------------------------------------
    # Properties
    # ----------------------------------------------------------------

    def get_IsConnected(self, *, metadata: MetadataDict) -> bool:
        if self._simulation_mode:
            return self._sim_connected
        return self._transport.is_connected

    def get_DisplayIcon(self, *, metadata: MetadataDict) -> bytes:
        icon_path = Path(__file__).parent.parent / "icon.png"
        return icon_path.read_bytes()

    def get_DeviceDescription(self, *, metadata: MetadataDict) -> str:
        return (
            "Datalogic Barcode Scanner — RS-232 serial barcode reader.\n"
            "\n"
            "Capabilities:\n"
            "- Triggers barcode scanning via STX control character\n"
            "- Reads 1D and 2D barcodes (Code 128, QR, Data Matrix, etc.)\n"
            "- Configurable serial port and baud rate (default 115200)\n"
            "- Automatic timeout detection (2 second default)\n"
            "- Cancel active scan via ETX control character\n"
            "\n"
            "Typical workflow:\n"
            "1. Connect (serial port, baud rate) — open RS-232 connection\n"
            "2. Scan — trigger scanner and read barcode data\n"
            "3. (Repeat Scan as needed)\n"
            "4. Disconnect — close serial connection\n"
            "\n"
            "Commands:\n"
            "- Connect: Open serial port (e.g. COM3, 115200 baud)\n"
            "- Scan: Trigger scan, returns barcode string\n"
            "- StopScanning: Cancel active scan (sends ETX)\n"
            "- Disconnect: Close serial connection\n"
            "\n"
            "Properties:\n"
            "- IsConnected: Whether serial port is open\n"
            "\n"
            "Notes:\n"
            "- Scanner must be powered and connected via RS-232 before Connect\n"
            "- ScanTimeout error raised if no barcode detected within 2 seconds\n"
            "- InvalidCommand error if scanner returns 'Invalid Cmd'\n"
            "- Auto-disconnects on communication errors"
        )

    # ----------------------------------------------------------------
    # Unobservable Commands
    # ----------------------------------------------------------------

    def Connect(self, SerialPort: str, BaudRate: int, *, metadata: MetadataDict) -> Connect_Responses:
        logger.info("Connect: port=%s, baud=%d, simulation=%s", SerialPort, BaudRate, self._simulation_mode)

        if self._simulation_mode:
            self._sim_connected = True
            return Connect_Responses()

        try:
            self._transport.connect(SerialPort, BaudRate)
        except ConnectionError as e:
            raise CommunicationError(str(e))

        return Connect_Responses()

    def Disconnect(self, *, metadata: MetadataDict) -> Disconnect_Responses:
        self._require_connected()
        logger.info("Disconnect")

        if self._simulation_mode:
            self._sim_connected = False
            return Disconnect_Responses()

        self._transport.disconnect()
        return Disconnect_Responses()

    def Scan(self, *, metadata: MetadataDict) -> Scan_Responses:
        self._require_connected()
        logger.info("Scan: simulation=%s", self._simulation_mode)

        if self._simulation_mode:
            time.sleep(0.3)
            barcode = self._generate_simulated_barcode()
            logger.info("Simulated barcode: %s", barcode)
            return Scan_Responses(BarcodeData=barcode)

        try:
            barcode = self._transport.scan()
        except ConnectionError as e:
            raise CommunicationError(str(e))
        except TimeoutError as e:
            raise ScanTimeout(str(e))
        except ValueError as e:
            raise InvalidCommand(str(e))

        logger.info("Scanned barcode: %s", barcode)
        return Scan_Responses(BarcodeData=barcode)

    def StopScanning(self, *, metadata: MetadataDict) -> StopScanning_Responses:
        self._require_connected()
        logger.info("StopScanning")

        if self._simulation_mode:
            return StopScanning_Responses()

        try:
            self._transport.stop_scanning()
        except ConnectionError as e:
            raise CommunicationError(str(e))

        return StopScanning_Responses()

    # ----------------------------------------------------------------
    # Helpers
    # ----------------------------------------------------------------

    @staticmethod
    def _generate_simulated_barcode() -> str:
        """Generate a random barcode string for simulation mode."""
        prefix = random.choice(["SIM", "TEST", "PLATE", "SAMPLE"])
        digits = "".join(random.choices(string.digits, k=8))
        return f"{prefix}-{digits}"
