# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.lockcontroller_impl import LockControllerImpl
from .feature_implementations.messagingclient_impl import MessagingClientImpl
from .feature_implementations.micronictubescanner_impl import MicronicTubeScannerImpl
from .feature_implementations.screenstreamer_impl import ScreenStreamerImpl
from .feature_implementations.simulationcontroller_impl import SimulationControllerImpl
from .generated.lockcontroller import LockControllerFeature
from .generated.messagingclient import MessagingClientFeature
from .generated.micronictubescanner import MicronicTubeScannerFeature
from .generated.screenstreamer import ScreenStreamerFeature
from .generated.simulationcontroller import SimulationControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "Micronic Tube Scanner"
        if description is None:
            description = "Micronic 2D tube-rack barcode scanner with screen streaming and messaging (SiLA 2)"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="MicronicTubeScanner",
            server_version="0.1",
            server_vendor_url="https://github.com/keyser",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        # Main feature
        self.micronictubescanner = MicronicTubeScannerImpl(self)
        self.set_feature_implementation(MicronicTubeScannerFeature, self.micronictubescanner)

        # Screen streamer
        self.screenstreamer = ScreenStreamerImpl(self)
        self.set_feature_implementation(ScreenStreamerFeature, self.screenstreamer)

        # Messaging client
        self.messagingclient = MessagingClientImpl(self)
        self.set_feature_implementation(MessagingClientFeature, self.messagingclient)

        # SimulationController
        self.simulationcontroller = SimulationControllerImpl(self)
        self.set_feature_implementation(SimulationControllerFeature, self.simulationcontroller)

        # LockController
        self.set_feature_implementation(LockControllerFeature, LockControllerImpl(self))
