# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from datetime import timedelta
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.venusmethodexecutor import (
    AbortMethod_Responses,
    GetCurrentRunData_Responses,
    GetDeckLayout_Responses,
    GetDetailedRunData_Responses,
    GetDevices_Responses,
    GetLoadedMethod_Responses,
    GetRunState_Responses,
    GetRuntimeData_Responses,
    GetRuntimeDevices_Responses,
    LoadMethod_IntermediateResponses,
    LoadMethod_Responses,
    PauseMethod_Responses,
    ResumeMethod_Responses,
    StartMethod_IntermediateResponses,
    StartMethod_Responses,
    UnloadMethod_Responses,
    VenusMethodExecutorBase,
)

if TYPE_CHECKING:
    from ..server import Server


class VenusMethodExecutorImpl(VenusMethodExecutorBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Default lifetime of observable command instances. Possible values:
        # None: Command instance is valid and stored in memory until server shutdown
        # datetime.timedelta: Command instance is deleted after this duration, can be increased during command runtime
        self.LoadMethod_default_lifetime_of_execution = timedelta(minutes=30)
        self.StartMethod_default_lifetime_of_execution = timedelta(minutes=30)

    def get_RuntimeStatus(self, *, metadata: MetadataDict) -> str:
        raise NotImplementedError  # TODO

    def get_IsMethodLoaded(self, *, metadata: MetadataDict) -> bool:
        raise NotImplementedError  # TODO

    def get_BaseUrl(self, *, metadata: MetadataDict) -> str:
        raise NotImplementedError  # TODO

    def get_DeviceDescription(self, *, metadata: MetadataDict) -> str:
        raise NotImplementedError  # TODO

    def PauseMethod(self, *, metadata: MetadataDict) -> PauseMethod_Responses:
        raise NotImplementedError  # TODO

    def ResumeMethod(self, *, metadata: MetadataDict) -> ResumeMethod_Responses:
        raise NotImplementedError  # TODO

    def AbortMethod(self, *, metadata: MetadataDict) -> AbortMethod_Responses:
        raise NotImplementedError  # TODO

    def UnloadMethod(self, *, metadata: MetadataDict) -> UnloadMethod_Responses:
        raise NotImplementedError  # TODO

    def GetDevices(self, *, metadata: MetadataDict) -> GetDevices_Responses:
        raise NotImplementedError  # TODO

    def GetDeckLayout(self, DeviceId: int, *, metadata: MetadataDict) -> GetDeckLayout_Responses:
        raise NotImplementedError  # TODO

    def GetCurrentRunData(self, *, metadata: MetadataDict) -> GetCurrentRunData_Responses:
        raise NotImplementedError  # TODO

    def GetRuntimeData(self, *, metadata: MetadataDict) -> GetRuntimeData_Responses:
        raise NotImplementedError  # TODO

    def GetDetailedRunData(self, RunGuid: str, *, metadata: MetadataDict) -> GetDetailedRunData_Responses:
        raise NotImplementedError  # TODO

    def GetRuntimeDevices(self, *, metadata: MetadataDict) -> GetRuntimeDevices_Responses:
        raise NotImplementedError  # TODO

    def GetLoadedMethod(self, *, metadata: MetadataDict) -> GetLoadedMethod_Responses:
        raise NotImplementedError  # TODO

    def GetRunState(self, *, metadata: MetadataDict) -> GetRunState_Responses:
        raise NotImplementedError  # TODO

    def LoadMethod(
        self,
        FilePath: str,
        Simulation: bool,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[LoadMethod_IntermediateResponses],
    ) -> LoadMethod_Responses:
        # set execution status from `waiting` to `running`
        instance.begin_execution()

        raise NotImplementedError  # TODO

    def StartMethod(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[StartMethod_IntermediateResponses],
    ) -> StartMethod_Responses:
        # set execution status from `waiting` to `running`
        instance.begin_execution()

        raise NotImplementedError  # TODO
