# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.barcodescanner_impl import BarcodeScannerImpl
from .feature_implementations.lockcontroller_impl import LockControllerImpl
from .feature_implementations.messagingclient_impl import MessagingClientImpl
from .feature_implementations.screenstreamer_impl import ScreenStreamerImpl
from .feature_implementations.simulationcontroller_impl import SimulationControllerImpl
from .generated.barcodescanner import BarcodeScannerFeature
from .generated.lockcontroller import LockControllerFeature
from .generated.messagingclient import MessagingClientFeature
from .generated.screenstreamer import ScreenStreamerFeature
from .generated.simulationcontroller import SimulationControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "Barcode Scanner"
        if description is None:
            description = "Datalogic barcode scanner (SiLA 2)"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="BarcodeScanner",
            server_version="0.1",
            server_vendor_url="https://github.com/keyser",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        # Main feature
        self.barcodescanner = BarcodeScannerImpl(self)
        self.set_feature_implementation(BarcodeScannerFeature, self.barcodescanner)

        # ScreenStreamer support
        self.screenstreamer = ScreenStreamerImpl(self)
        self.set_feature_implementation(ScreenStreamerFeature, self.screenstreamer)

        # MessagingClient support
        self.messagingclient = MessagingClientImpl(self)
        self.set_feature_implementation(MessagingClientFeature, self.messagingclient)

        # SimulationController support
        self.simulationcontroller = SimulationControllerImpl(self)
        self.set_feature_implementation(SimulationControllerFeature, self.simulationcontroller)

        # LockController support
        self.set_feature_implementation(LockControllerFeature, LockControllerImpl(self))
