# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.messagingclient_impl import MessagingClientImpl
from .feature_implementations.platereader_impl import PlateReaderImpl
from .feature_implementations.screenstreamer_impl import ScreenStreamerImpl
from .generated.messagingclient import MessagingClientFeature
from .generated.platereader import PlateReaderFeature
from .generated.screenstreamer import ScreenStreamerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "Plate Reader"
        if description is None:
            description = "Simulated microplate reader for SiLA 2 learning"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="PlateReader",
            server_version="0.1",
            server_vendor_url="https://github.com/keyser",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.platereader = PlateReaderImpl(self)
        self.set_feature_implementation(PlateReaderFeature, self.platereader)

        # Screen streamer
        self.screenstreamer = ScreenStreamerImpl(self)
        self.set_feature_implementation(ScreenStreamerFeature, self.screenstreamer)

        # Messaging client
        self.messagingclient = MessagingClientImpl(self)
        self.set_feature_implementation(MessagingClientFeature, self.messagingclient)
