# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import logging
import random
import threading
import time
from datetime import timedelta
from pathlib import Path
from typing import TYPE_CHECKING, List

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.pheniximager import (
    AcquisitionTimeout,
    CommunicationError,
    Connect_Responses,
    DeviceError,
    Disconnect_Responses,
    GoIdle_Responses,
    GoStandby_Responses,
    NotConnected,
    PhenixImagerBase,
    RunAcquisitionProtocol_IntermediateResponses,
    RunAcquisitionProtocol_Responses,
    StageIn_Responses,
    StageMotionTimeout,
    StageOut_Responses,
    Stop_Responses,
)
from ..rci_transport import (
    DeviceState,
    PhenixStatus,
    RCITransport,
    StagePosition,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)

# Simulated protocol names
_SIM_PROTOCOLS = [
    "BrightField_10x",
    "Confocal_40x_3ch",
    "Confocal_63x_DAPI_GFP",
    "WidefieldFluorescence_20x",
    "LiveCell_TimeLapse_10min",
]


class PhenixImagerImpl(PhenixImagerBase):
    """PerkinElmer Opera Phenix high-content imager SiLA 2 feature implementation.

    In simulation mode, all commands are simulated without RCI communication.
    In real mode, commands are forwarded to the instrument via RCI transport.
    """

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.RunAcquisitionProtocol_default_lifetime_of_execution = timedelta(minutes=660)

        self._transport = RCITransport()
        self._simulation_mode: bool = True
        self._lock = threading.Lock()

        # Simulation state
        self._sim_connected: bool = False
        self._sim_device_name: str = ""
        self._sim_device_state: str = "Offline"
        self._sim_stage_position: str = "Transfer"
        self._sim_plate_detected: bool = False
        self._sim_protocols: List[str] = []
        self._sim_running: bool = False

    def _require_connected(self) -> None:
        """Raise NotConnected if instrument is not connected."""
        if self._simulation_mode:
            if not self._sim_connected:
                raise NotConnected()
        else:
            if not self._transport.is_connected:
                raise NotConnected()

    def _send_command(self, fn, *args, **kwargs):
        """Call a transport method, translating exceptions to SiLA errors."""
        try:
            return fn(*args, **kwargs)
        except ConnectionError as e:
            raise CommunicationError(str(e))
        except TimeoutError as e:
            raise CommunicationError(str(e))
        except RuntimeError as e:
            raise DeviceError(str(e))

    # ----------------------------------------------------------------
    # Standard Properties
    # ----------------------------------------------------------------

    def get_DisplayIcon(self, *, metadata: MetadataDict) -> bytes:
        icon_path = Path(__file__).parent.parent / "icon.png"
        return icon_path.read_bytes()

    def get_DeviceDescription(self, *, metadata: MetadataDict) -> str:
        return (
            "PerkinElmer Opera Phenix — high-content screening imager.\n"
            "\n"
            "Capabilities:\n"
            "- Automated confocal and widefield fluorescence microscopy\n"
            "- Multi-well plate imaging (96, 384, 1536 well formats)\n"
            "- Motorized stage with Transfer/Operate positions for robot integration\n"
            "- Acquisition protocols with 0-100% progress tracking\n"
            "- Plate barcode association for sample tracking\n"
            "- Remote control via RCI protocol (ports 8213/8300)\n"
            "\n"
            "Typical workflow:\n"
            "1. Connect (hostname) — establish RCI connection, query protocols\n"
            "2. StageIn (barcode) — move stage to Operate position (robot loads plate first)\n"
            "3. RunAcquisitionProtocol (protocol, barcode, timeout) — image the plate\n"
            "   (observable: reports progress 0-100% with well-by-well updates)\n"
            "   (auto-ejects stage when complete)\n"
            "4. (Robot removes plate from Transfer position)\n"
            "5. Repeat steps 2-4 for additional plates\n"
            "6. GoStandby or Disconnect when done\n"
            "\n"
            "Commands:\n"
            "- Connect: Open RCI connection to Phenix host\n"
            "- StageIn: Move stage to imaging position (LOAD)\n"
            "- StageOut: Move stage to transfer position (EJECT)\n"
            "- RunAcquisitionProtocol: Execute imaging protocol (observable)\n"
            "- Stop: Abort running acquisition\n"
            "- GoIdle: Return device to Idle state\n"
            "- GoStandby: Enter low-power standby mode\n"
            "- Disconnect: Close RCI connection\n"
            "\n"
            "Properties:\n"
            "- IsConnected, DeviceState, StagePosition, PlateDetected\n"
            "- AvailableProtocols: list of imaging protocols on the instrument\n"
            "\n"
            "Notes:\n"
            "- Stage must be in Transfer position for robot plate loading/unloading\n"
            "- Stage motion timeout: 2 minutes\n"
            "- Default acquisition timeout: 600 minutes (configurable per run)\n"
            "- Device states: Operate, Idle, Standby, Offline, Service"
        )

    # ----------------------------------------------------------------
    # Device-Specific Properties
    # ----------------------------------------------------------------

    def get_IsConnected(self, *, metadata: MetadataDict) -> bool:
        if self._simulation_mode:
            return self._sim_connected
        return self._transport.is_connected

    def get_DeviceState(self, *, metadata: MetadataDict) -> str:
        if self._simulation_mode:
            return self._sim_device_state
        status = self._transport.status
        return status.device_state.name if status else "Offline"

    def get_StagePosition(self, *, metadata: MetadataDict) -> str:
        if self._simulation_mode:
            return self._sim_stage_position
        status = self._transport.status
        return status.stage_position.name if status else "Home"

    def get_PlateDetected(self, *, metadata: MetadataDict) -> bool:
        if self._simulation_mode:
            return self._sim_plate_detected
        status = self._transport.status
        if status:
            return status.plate_detector.value == 1
        return False

    def get_AvailableProtocols(self, *, metadata: MetadataDict) -> List[str]:
        if self._simulation_mode:
            return self._sim_protocols
        return self._transport.protocols

    # ----------------------------------------------------------------
    # Unobservable Commands
    # ----------------------------------------------------------------

    def Connect(self, PhenixHost: str, *, metadata: MetadataDict) -> Connect_Responses:
        logger.info("Connect: host=%s, simulation=%s", PhenixHost, self._simulation_mode)

        if self._simulation_mode:
            self._sim_connected = True
            self._sim_device_name = "Opera Phenix (Simulated)"
            self._sim_device_state = "Idle"
            self._sim_stage_position = "Transfer"
            self._sim_plate_detected = False
            self._sim_protocols = list(_SIM_PROTOCOLS)
            self._sim_running = False
            return Connect_Responses(DeviceName=self._sim_device_name)

        try:
            device_name = self._transport.connect(PhenixHost)
        except ConnectionError as e:
            raise CommunicationError(str(e))

        return Connect_Responses(DeviceName=device_name)

    def Disconnect(self, *, metadata: MetadataDict) -> Disconnect_Responses:
        self._require_connected()
        logger.info("Disconnect")

        if self._simulation_mode:
            self._sim_connected = False
            self._sim_device_state = "Offline"
            self._sim_protocols = []
            return Disconnect_Responses()

        self._transport.disconnect()
        return Disconnect_Responses()

    def StageIn(self, PlateBarcode: str, *, metadata: MetadataDict) -> StageIn_Responses:
        self._require_connected()
        logger.info("StageIn: barcode=%s", PlateBarcode)

        if self._simulation_mode:
            time.sleep(0.5)
            self._sim_stage_position = "Operate"
            self._sim_plate_detected = True
            self._sim_device_state = "Idle"
            return StageIn_Responses()

        try:
            self._transport.send_load(PlateBarcode)
        except RuntimeError as e:
            raise DeviceError(str(e))
        except TimeoutError as e:
            raise StageMotionTimeout(str(e))
        except ConnectionError as e:
            raise CommunicationError(str(e))

        return StageIn_Responses()

    def StageOut(self, PlateBarcode: str, *, metadata: MetadataDict) -> StageOut_Responses:
        self._require_connected()
        logger.info("StageOut: barcode=%s", PlateBarcode)

        if self._simulation_mode:
            time.sleep(0.5)
            self._sim_stage_position = "Transfer"
            self._sim_device_state = "Idle"
            return StageOut_Responses()

        try:
            self._transport.send_eject(PlateBarcode)
        except RuntimeError as e:
            raise DeviceError(str(e))
        except TimeoutError as e:
            raise StageMotionTimeout(str(e))
        except ConnectionError as e:
            raise CommunicationError(str(e))

        return StageOut_Responses()

    def Stop(self, *, metadata: MetadataDict) -> Stop_Responses:
        self._require_connected()
        logger.info("Stop")

        if self._simulation_mode:
            self._sim_running = False
            self._sim_device_state = "Idle"
            return Stop_Responses()

        self._send_command(self._transport.send_stop)
        return Stop_Responses()

    def GoIdle(self, *, metadata: MetadataDict) -> GoIdle_Responses:
        self._require_connected()
        logger.info("GoIdle")

        if self._simulation_mode:
            self._sim_device_state = "Idle"
            return GoIdle_Responses()

        self._send_command(self._transport.send_idle)
        return GoIdle_Responses()

    def GoStandby(self, DurationSeconds: int, *, metadata: MetadataDict) -> GoStandby_Responses:
        self._require_connected()
        logger.info("GoStandby: duration=%ds", DurationSeconds)

        if self._simulation_mode:
            self._sim_device_state = "Standby"
            return GoStandby_Responses()

        self._send_command(self._transport.send_standby, DurationSeconds)
        return GoStandby_Responses()

    # ----------------------------------------------------------------
    # Observable Commands
    # ----------------------------------------------------------------

    def RunAcquisitionProtocol(
        self,
        ProtocolName: str,
        PlateBarcode: str,
        TimeoutMinutes: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[
            RunAcquisitionProtocol_IntermediateResponses
        ],
    ) -> RunAcquisitionProtocol_Responses:
        self._require_connected()
        logger.info(
            "RunAcquisitionProtocol: protocol=%s, barcode=%s, timeout=%dm",
            ProtocolName, PlateBarcode, TimeoutMinutes,
        )

        instance.begin_execution()
        instance.lifetime_of_execution = timedelta(minutes=TimeoutMinutes + 5)
        instance.estimated_remaining_time = timedelta(minutes=TimeoutMinutes)

        if self._simulation_mode:
            return self._run_acquisition_simulated(
                ProtocolName, PlateBarcode, TimeoutMinutes, instance
            )

        return self._run_acquisition_real(
            ProtocolName, PlateBarcode, TimeoutMinutes, instance
        )

    def _run_acquisition_simulated(
        self,
        protocol_name: str,
        barcode: str,
        timeout_minutes: int,
        instance: ObservableCommandInstanceWithIntermediateResponses[
            RunAcquisitionProtocol_IntermediateResponses
        ],
    ) -> RunAcquisitionProtocol_Responses:
        """Simulate a plate acquisition with well-by-well progress."""
        # Ensure stage is in Operate
        if self._sim_stage_position != "Operate":
            self._sim_stage_position = "Operate"
            self._sim_plate_detected = True

        self._sim_device_state = "Operate"
        self._sim_running = True

        # Simulate 96-well plate: 8 rows x 12 cols
        total_wells = 96
        well = 0

        for row in range(1, 9):
            for col in range(1, 13):
                if not self._sim_running:
                    self._sim_device_state = "Idle"
                    raise DeviceError("Acquisition stopped by user")

                well += 1
                progress = well / total_wells
                instance.progress = progress
                remaining = (total_wells - well) * 0.1
                instance.estimated_remaining_time = timedelta(seconds=remaining)
                instance.send_intermediate_response(
                    RunAcquisitionProtocol_IntermediateResponses(
                        ProgressInfo=f"Well R{row}C{col} - {int(progress * 100)}%"
                    )
                )
                time.sleep(0.1)

        # Auto stage-out
        self._sim_stage_position = "Transfer"
        self._sim_device_state = "Idle"
        self._sim_running = False

        return RunAcquisitionProtocol_Responses(
            Status=f"Acquisition '{protocol_name}' completed successfully"
        )

    def _run_acquisition_real(
        self,
        protocol_name: str,
        barcode: str,
        timeout_minutes: int,
        instance: ObservableCommandInstanceWithIntermediateResponses[
            RunAcquisitionProtocol_IntermediateResponses
        ],
    ) -> RunAcquisitionProtocol_Responses:
        """Execute real acquisition via RCI, tracking progress."""
        # Ensure stage is in Operate position
        status = self._send_command(self._transport.get_status, barcode)
        if status.stage_position != StagePosition.Operate:
            try:
                self._transport.send_load(barcode)
            except TimeoutError as e:
                raise StageMotionTimeout(str(e))
            except RuntimeError as e:
                raise DeviceError(str(e))

        # Track progress via callback
        completion_event = threading.Event()
        last_progress = [0]

        def on_progress(status: PhenixStatus) -> None:
            pct = status.progress
            if pct > last_progress[0]:
                last_progress[0] = pct
                instance.progress = pct / 100.0
                instance.send_intermediate_response(
                    RunAcquisitionProtocol_IntermediateResponses(
                        ProgressInfo=f"Well {status.detailed_progress}/{status.well_count} - {pct}%"
                    )
                )
            if pct >= 100:
                completion_event.set()

        # Send RUN command
        try:
            self._transport.send_run(protocol_name, barcode, progress_callback=on_progress)
        except RuntimeError as e:
            raise DeviceError(str(e))
        except ConnectionError as e:
            raise CommunicationError(str(e))

        # Wait for completion
        if not completion_event.wait(timeout=timeout_minutes * 60):
            raise AcquisitionTimeout(
                f"Acquisition '{protocol_name}' did not complete within {timeout_minutes} minutes"
            )

        # Auto stage-out
        try:
            self._transport.send_eject(barcode)
        except Exception as e:
            logger.warning("Auto stage-out failed: %s", e)

        return RunAcquisitionProtocol_Responses(
            Status=f"Acquisition '{protocol_name}' completed successfully"
        )
