# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Multidrop Combi device feature implementation
from __future__ import annotations

import json
import logging
import threading
import time
from datetime import timedelta
from pathlib import Path
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstance, ObservableCommandInstanceWithIntermediateResponses

from ..generated.multidropcombi import (
    Abort_Responses,
    AcknowledgeError_Responses,
    CommunicationError,
    Connect_Responses,
    Disconnect_Responses,
    Dispense_IntermediateResponses,
    Dispense_Responses,
    Empty_Responses,
    InstrumentError,
    MoveOut_Responses,
    MultidropCombiBase,
    NotConnected,
    Prime_Responses,
    Restart_Responses,
    SetCassetteType_Responses,
    SetColumnVolume_Responses,
    SetDispensingHeight_Responses,
    SetPlateType_Responses,
    SetPumpSpeed_Responses,
    Shake_Responses,
)
from sila_server_common.transports.device_config import load_device_config, save_device_config

from ..serial_transport import MultidropSerialTransport

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)

# Per-command timeout constants (seconds)
COMMAND_TIMEOUTS: dict[str, float] = {
    "SPL": 5.0,
    "SCT": 5.0,
    "SCV": 5.0,
    "SDH": 5.0,
    "SPS": 5.0,
    "EAK": 5.0,
    "POU": 10.0,
    "RST": 10.0,
    "PRI": 30.0,
    "EMP": 30.0,
    "SHA": 60.0,
}
VOLUME_TIMEOUT_SCALE = 1.0 / 100.0  # +1s per 100 volume units


class MultidropCombiImpl(MultidropCombiBase):
    """Multidrop Combi reagent dispenser SiLA 2 feature implementation."""

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.Dispense_default_lifetime_of_execution = timedelta(minutes=10)
        self.Shake_default_lifetime_of_execution = timedelta(minutes=5)

        self._transport = MultidropSerialTransport()
        self._simulation_mode: bool = True
        self._lock = threading.Semaphore(1)

        # Simulation state
        self._sim_connected: bool = False
        self._sim_instrument_name: str = ""
        self._sim_firmware_version: str = ""
        self._sim_serial_number: str = ""
        self._sim_primed: bool = False
        self._sim_plate_type: int = 0
        self._sim_cassette_type: int = 0
        self._sim_column_volumes: dict[int, int] = {}
        self._sim_dispensing_height: int = 0
        self._sim_pump_speed: int = 50

        # Activity log (for DeviceStatus push)
        self._activity_log: list[str] = []

        # Cached serial port from device_config.json
        self._cached_serial_port: str = ""

    def start(self) -> None:
        super().start()
        # Load persisted serial port
        config = load_device_config(self.parent_server._server_package)
        self._cached_serial_port = (config or {}).get("serial_port", "")
        # Push initial observable property values
        self.update_IsConnected(False)
        self.update_IsPrimed(False)
        self.update_InstrumentName("")
        self.update_FirmwareVersion("")
        self._push_device_status()
        logger.info("MultidropCombi started")

    def _push_device_status(self, activity: str | None = None) -> None:
        """Push a full device status update via the DeviceStatus observable property."""
        if activity:
            ts = time.strftime("%H:%M:%S")
            self._activity_log.append(f"[{ts}] {activity}")
            # Keep last 100 entries
            if len(self._activity_log) > 100:
                self._activity_log = self._activity_log[-100:]

        is_connected = self._sim_connected if self._simulation_mode else self._transport.is_connected
        status = {
            "isConnected": is_connected,
            "isPrimed": self._sim_primed,
            "instrumentName": self._sim_instrument_name if self._simulation_mode else self._transport.instrument_name,
            "firmwareVersion": self._sim_firmware_version if self._simulation_mode else self._transport.firmware_version,
            "serialNumber": self._sim_serial_number if self._simulation_mode else self._transport.serial_number,
            "simulationMode": self._simulation_mode,
            "plateType": self._sim_plate_type,
            "cassetteType": self._sim_cassette_type,
            "pumpSpeed": self._sim_pump_speed,
            "dispensingHeight": self._sim_dispensing_height,
            "columnVolumes": self._sim_column_volumes,
            "activityLog": self._activity_log[-50:],
            "configuredSerialPort": self._cached_serial_port,
        }
        self.update_DeviceStatus(json.dumps(status))

    def _require_connected(self) -> None:
        """Raise NotConnected if instrument is not in remote control mode."""
        if self._simulation_mode:
            if not self._sim_connected:
                raise NotConnected()
        else:
            if not self._transport.is_connected:
                raise NotConnected()

    def _send_command(self, cmd: str, timeout: float | None = None) -> list[str]:
        """Send a serial command, translating exceptions to SiLA errors."""
        cmd_code = cmd.split()[0]
        logger.debug("Sending command: %s", cmd)
        try:
            result = self._transport.send_command(cmd, timeout=timeout)
            logger.debug("Command %s OK, %d data lines", cmd_code, len(result))
            return result
        except ConnectionError as e:
            logger.error("Communication error on %s: %s", cmd_code, e)
            raise CommunicationError(str(e))
        except RuntimeError as e:
            logger.error("Instrument error on %s: %s", cmd_code, e)
            raise InstrumentError(str(e))

    # ----------------------------------------------------------------
    # Unobservable Properties
    # ----------------------------------------------------------------

    def get_DisplayIcon(self, *, metadata: MetadataDict) -> bytes:
        icon_path = Path(__file__).parent.parent / "icon.png"
        return icon_path.read_bytes()

    def get_DeviceDescription(self, *, metadata: MetadataDict) -> str:
        return (
            "Thermo Scientific Multidrop Combi — bulk reagent dispenser for microplates.\n"
            "\n"
            "Capabilities:\n"
            "- Dispenses 0.5 uL to 1 mL per well (volumes specified in 1/10 uL units)\n"
            "- Supports 96, 384, and 1536 well plate formats (30 plate type codes)\n"
            "- Per-column volume control (columns 1-48, or 0 for all columns)\n"
            "- Cassette types 0-3 (standard, small volume, etc.)\n"
            "- Adjustable pump speed (1-100%), dispensing height (1/100 mm units)\n"
            "- Plate shaking (configurable time in 1/100 s, distance 1-5 mm, speed 1-20 Hz)\n"
            "- Prime and empty hoses with mode selection (all tubes, even, odd, by cassette)\n"
            "\n"
            "Typical workflow:\n"
            "1. Connect (serial port) — enters remote control mode\n"
            "2. SetPlateType — select plate format\n"
            "3. SetCassetteType — select dispensing cassette\n"
            "4. Prime — fill hoses with reagent\n"
            "5. SetColumnVolume — set volume per column (or all columns)\n"
            "6. Dispense — dispense into plate (observable, reports column/row progress)\n"
            "7. Shake — optional plate mixing (observable)\n"
            "8. Empty — reverse pump to clear hoses\n"
            "9. Disconnect — exit remote control mode\n"
            "\n"
            "Units:\n"
            "- Volumes: 1/10 uL (e.g. 100 = 10 uL)\n"
            "- Shake time: 1/100 seconds (e.g. 500 = 5 s)\n"
            "- Dispensing height: 1/100 mm\n"
            "\n"
            "Additional commands: Abort (cancel running operation), MoveOut (plate carrier to "
            "loading position), AcknowledgeError (clear instrument error), SetPumpSpeed, "
            "SetDispensingHeight, Restart (reboot instrument, requires reconnect).\n"
            "\n"
            "Observable properties (IsConnected, IsPrimed, InstrumentName, FirmwareVersion, "
            "DeviceStatus) push state changes in real-time for reactive UI updates."
        )

    # ----------------------------------------------------------------
    # Unobservable Commands
    # ----------------------------------------------------------------

    def Connect(self, SerialPort: str, *, metadata: MetadataDict) -> Connect_Responses:
        logger.info("Connect: port=%s, simulation=%s", SerialPort, self._simulation_mode,
                     extra={"category": "command", "command_name": "Connect"})

        if self._simulation_mode:
            self._sim_connected = True
            self._sim_instrument_name = "Multidrop Combi (Simulated)"
            self._sim_firmware_version = "SIM-1.0.0"
            self._sim_serial_number = "SIM-00000"
            self._sim_primed = False
            # Push observable updates
            self.update_IsConnected(True)
            self.update_IsPrimed(False)
            self.update_InstrumentName(self._sim_instrument_name)
            self.update_FirmwareVersion(self._sim_firmware_version)
            self._push_device_status(f"Connected to {SerialPort} (simulation)")
            save_device_config(self.parent_server._server_package, {"serial_port": SerialPort})
            self._cached_serial_port = SerialPort
            return Connect_Responses(
                InstrumentName=self._sim_instrument_name,
                FirmwareVersion=self._sim_firmware_version,
                SerialNumber=self._sim_serial_number,
            )

        try:
            info = self._transport.connect(SerialPort)
        except ConnectionError as e:
            logger.error("Connect failed: %s", e)
            raise CommunicationError(str(e))

        self._sim_primed = False
        # Push observable updates
        self.update_IsConnected(True)
        self.update_IsPrimed(False)
        self.update_InstrumentName(info["instrument_name"])
        self.update_FirmwareVersion(info["firmware_version"])
        self._push_device_status(f"Connected to {SerialPort}: {info['instrument_name']} FW {info['firmware_version']}")
        save_device_config(self.parent_server._server_package, {"serial_port": SerialPort})
        logger.info("Connected to %s (FW: %s)", info["instrument_name"], info["firmware_version"])
        return Connect_Responses(
            InstrumentName=info["instrument_name"],
            FirmwareVersion=info["firmware_version"],
            SerialNumber=info["serial_number"],
        )

    def Disconnect(self, *, metadata: MetadataDict) -> Disconnect_Responses:
        logger.info("Disconnect", extra={"category": "command", "command_name": "Disconnect"})

        if self._simulation_mode:
            self._sim_connected = False
            self._sim_instrument_name = ""
            self._sim_firmware_version = ""
            self._sim_serial_number = ""
            self._sim_primed = False
        else:
            try:
                self._transport.disconnect()
            except Exception:
                logger.warning("Disconnect failed, forcing port closed")
                try:
                    self._transport._serial.close()
                except Exception:
                    pass
                self._transport._serial = None
            self._sim_primed = False

        # Push observable updates
        self.update_IsConnected(False)
        self.update_IsPrimed(False)
        self.update_InstrumentName("")
        self.update_FirmwareVersion("")
        self._push_device_status("Disconnected")
        return Disconnect_Responses()

    def Abort(self, *, metadata: MetadataDict) -> Abort_Responses:
        self._require_connected()
        logger.info("Abort")

        if not self._simulation_mode:
            self._transport.abort()

        self._push_device_status("Abort sent")
        return Abort_Responses()

    def Prime(self, Volume: int, Mode: int, *, metadata: MetadataDict) -> Prime_Responses:
        self._require_connected()
        if Volume < 10 or Volume > 100000:
            raise InstrumentError(f"Volume must be 10-100000 (1/10 µL), got {Volume}")
        if Mode < 0 or Mode > 3:
            raise InstrumentError(f"Mode must be 0-3, got {Mode}")
        logger.info("Prime: volume=%d, mode=%d", Volume, Mode,
                     extra={"category": "command", "command_name": "Prime"})

        if self._simulation_mode:
            time.sleep(0.5)
            self._sim_primed = True
        else:
            timeout = COMMAND_TIMEOUTS["PRI"] + Volume * VOLUME_TIMEOUT_SCALE
            # Mode is optional: omit for standard prime (mode=0 means "stop continuous",
            # NOT "prime this volume"). Only include mode for continuous/calibration.
            if Mode == 0:
                self._send_command(f"PRI {Volume}", timeout=timeout)
            else:
                self._send_command(f"PRI {Volume} {Mode}", timeout=timeout)
            self._sim_primed = True

        self.update_IsPrimed(True)
        self._push_device_status(f"Primed (volume={Volume}, mode={Mode})")
        return Prime_Responses()

    def Empty(self, Volume: int, Mode: int, *, metadata: MetadataDict) -> Empty_Responses:
        self._require_connected()
        if Volume < 10 or Volume > 100000:
            raise InstrumentError(f"Volume must be 10-100000 (1/10 µL), got {Volume}")
        if Mode < 0 or Mode > 1:
            raise InstrumentError(f"Mode must be 0-1, got {Mode}")
        logger.info("Empty: volume=%d, mode=%d", Volume, Mode)

        if self._simulation_mode:
            time.sleep(0.5)
        else:
            timeout = COMMAND_TIMEOUTS["EMP"] + Volume * VOLUME_TIMEOUT_SCALE
            # Mode is optional: omit for standard empty (mode=0 means "stop continuous").
            if Mode == 0:
                self._send_command(f"EMP {Volume}", timeout=timeout)
            else:
                self._send_command(f"EMP {Volume} {Mode}", timeout=timeout)

        self._push_device_status(f"Emptied (volume={Volume}, mode={Mode})")
        return Empty_Responses()

    def MoveOut(self, *, metadata: MetadataDict) -> MoveOut_Responses:
        self._require_connected()
        logger.info("MoveOut")

        if self._simulation_mode:
            time.sleep(0.3)
        else:
            self._send_command("POU", timeout=COMMAND_TIMEOUTS["POU"])

        self._push_device_status("Plate carrier moved out")
        return MoveOut_Responses()

    def AcknowledgeError(self, *, metadata: MetadataDict) -> AcknowledgeError_Responses:
        self._require_connected()
        logger.info("AcknowledgeError")

        if not self._simulation_mode:
            self._send_command("EAK", timeout=COMMAND_TIMEOUTS["EAK"])

        self._push_device_status("Error acknowledged")
        return AcknowledgeError_Responses()

    def SetPlateType(self, PlateType: int, *, metadata: MetadataDict) -> SetPlateType_Responses:
        self._require_connected()
        if PlateType < 0 or PlateType > 29:
            raise InstrumentError(f"PlateType must be 0-29, got {PlateType}")
        logger.info("SetPlateType: %d", PlateType)

        if self._simulation_mode:
            self._sim_plate_type = PlateType
        else:
            self._send_command(f"SPL {PlateType}", timeout=COMMAND_TIMEOUTS["SPL"])
            self._sim_plate_type = PlateType

        self._push_device_status(f"Plate type set to {PlateType}")
        return SetPlateType_Responses()

    def SetCassetteType(self, CassetteType: int, *, metadata: MetadataDict) -> SetCassetteType_Responses:
        self._require_connected()
        if CassetteType < 0 or CassetteType > 3:
            raise InstrumentError(f"CassetteType must be 0-3, got {CassetteType}")
        logger.info("SetCassetteType: %d", CassetteType)

        if self._simulation_mode:
            self._sim_cassette_type = CassetteType
        else:
            self._send_command(f"SCT {CassetteType}", timeout=COMMAND_TIMEOUTS["SCT"])
            self._sim_cassette_type = CassetteType

        self._push_device_status(f"Cassette type set to {CassetteType}")
        return SetCassetteType_Responses()

    def SetColumnVolume(self, Column: int, Volume: int, *, metadata: MetadataDict) -> SetColumnVolume_Responses:
        self._require_connected()
        if Column < 0 or Column > 48:
            raise InstrumentError(f"Column must be 0-48 (0=all), got {Column}")
        if Volume < 0 or Volume > 25000:
            raise InstrumentError(f"Volume must be 0-25000 (1/10 µL), got {Volume}")
        logger.info("SetColumnVolume: column=%d, volume=%d", Column, Volume)

        if self._simulation_mode:
            self._sim_column_volumes[Column] = Volume
        else:
            self._send_command(f"SCV {Column} {Volume}", timeout=COMMAND_TIMEOUTS["SCV"])
            self._sim_column_volumes[Column] = Volume

        self._push_device_status(f"Column {Column} volume set to {Volume}")
        return SetColumnVolume_Responses()

    def SetDispensingHeight(self, Height: int, *, metadata: MetadataDict) -> SetDispensingHeight_Responses:
        self._require_connected()
        if Height < 500 or Height > 5500:
            raise InstrumentError(f"Height must be 500-5500 (1/100 mm), got {Height}")
        logger.info("SetDispensingHeight: %d", Height)

        if self._simulation_mode:
            self._sim_dispensing_height = Height
        else:
            self._send_command(f"SDH {Height}", timeout=COMMAND_TIMEOUTS["SDH"])
            self._sim_dispensing_height = Height

        self._push_device_status(f"Dispensing height set to {Height}")
        return SetDispensingHeight_Responses()

    def SetPumpSpeed(self, Speed: int, *, metadata: MetadataDict) -> SetPumpSpeed_Responses:
        self._require_connected()
        if Speed < 1 or Speed > 100:
            raise InstrumentError(f"Speed must be 1-100, got {Speed}")
        logger.info("SetPumpSpeed: %d%%", Speed)

        if self._simulation_mode:
            self._sim_pump_speed = Speed
        else:
            self._send_command(f"SPS {Speed}", timeout=COMMAND_TIMEOUTS["SPS"])
            self._sim_pump_speed = Speed

        self._push_device_status(f"Pump speed set to {Speed}%")
        return SetPumpSpeed_Responses()

    def Restart(self, *, metadata: MetadataDict) -> Restart_Responses:
        logger.info("Restart")

        if self._simulation_mode:
            self._sim_connected = False
            self._sim_primed = False
            time.sleep(0.5)
        else:
            # Try to send RST even if not connected — the instrument may be
            # persisting a stale remote-control session and needs a reboot
            # before it will accept a new VER.
            if self._transport.is_connected:
                try:
                    self._send_command("RST", timeout=COMMAND_TIMEOUTS["RST"])
                except Exception:
                    logger.warning("RST command failed, closing port anyway")
            try:
                self._transport._serial.close()
            except Exception:
                pass
            self._transport._serial = None
            self._sim_primed = False

        # Push observable updates
        self.update_IsConnected(False)
        self.update_IsPrimed(False)
        self.update_InstrumentName("")
        self.update_FirmwareVersion("")
        self._push_device_status("Instrument restarted — reconnect required")
        return Restart_Responses()

    # ----------------------------------------------------------------
    # Observable Commands
    # ----------------------------------------------------------------

    def Dispense(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[Dispense_IntermediateResponses],
    ) -> Dispense_Responses:
        self._require_connected()
        if not self._sim_primed:
            raise InstrumentError("Must prime before dispensing")
        logger.info("Dispense: simulation=%s", self._simulation_mode,
                     extra={"category": "command", "command_name": "Dispense"})

        instance.begin_execution()
        self._push_device_status("Dispensing...")

        if self._simulation_mode:
            result = self._dispense_simulated(instance)
        else:
            result = self._dispense_real(instance)

        self._push_device_status("Dispense completed")
        return result

    def _dispense_simulated(
        self,
        instance: ObservableCommandInstanceWithIntermediateResponses[Dispense_IntermediateResponses],
    ) -> Dispense_Responses:
        total_columns = 12
        total_rows = 8
        total_steps = total_columns * total_rows

        instance.estimated_remaining_time = timedelta(seconds=total_steps * 0.1)
        step = 0

        for col in range(1, total_columns + 1):
            for row in range(1, total_rows + 1):
                step += 1
                progress = step / total_steps
                instance.progress = progress
                instance.estimated_remaining_time = timedelta(
                    seconds=(total_steps - step) * 0.1
                )
                instance.send_intermediate_response(
                    Dispense_IntermediateResponses(ColumnRow=f"Col {col} Row {row}")
                )
                time.sleep(0.1)

        logger.info("Dispense completed (simulation)")
        return Dispense_Responses(Status="Dispense completed successfully")

    def _dispense_real(
        self,
        instance: ObservableCommandInstanceWithIntermediateResponses[Dispense_IntermediateResponses],
    ) -> Dispense_Responses:
        try:
            for line in self._transport.send_command_streaming("DIS"):
                instance.send_intermediate_response(
                    Dispense_IntermediateResponses(ColumnRow=line)
                )
        except ConnectionError as e:
            logger.error("Dispense communication error: %s", e)
            raise CommunicationError(str(e))
        except RuntimeError as e:
            logger.error("Dispense instrument error: %s", e)
            raise InstrumentError(str(e))
        except Exception as e:
            logger.error("Dispense failed: %s", e)
            raise CommunicationError(f"Dispense failed: {e}")

        logger.info("Dispense completed (real)")
        return Dispense_Responses(Status="Dispense completed successfully")

    def Shake(
        self,
        Time: int,
        Distance: int,
        Speed: int,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Shake_Responses:
        self._require_connected()
        if Time < 1:
            raise InstrumentError(f"Shake time must be >= 1 (1/100 s), got {Time}")
        if Distance < 1 or Distance > 5:
            raise InstrumentError(f"Shake distance must be 1-5 mm, got {Distance}")
        if Speed < 1 or Speed > 20:
            raise InstrumentError(f"Shake speed must be 1-20 Hz, got {Speed}")
        # Validate distance/speed combination per manual Table 3-2
        max_dist_for_speed = {9:4, 10:3, 11:3, 12:2, 13:2, 14:2, 15:1, 16:1, 17:1, 18:1, 19:1, 20:1}
        max_dist = max_dist_for_speed.get(Speed, 5)
        if Distance > max_dist:
            raise InstrumentError(f"Distance {Distance} mm too high for speed {Speed} Hz (max {max_dist} mm)")
        logger.info("Shake: time=%d, distance=%d, speed=%d", Time, Distance, Speed)

        instance.begin_execution()
        self._push_device_status(f"Shaking (time={Time}, dist={Distance}, speed={Speed})...")

        if self._simulation_mode:
            shake_seconds = Time / 100.0
            instance.estimated_remaining_time = timedelta(seconds=shake_seconds)

            UPDATE_INTERVAL = 0.2
            elapsed = 0.0
            while elapsed < shake_seconds:
                time.sleep(min(UPDATE_INTERVAL, shake_seconds - elapsed))
                elapsed += UPDATE_INTERVAL
                progress = min(1.0, elapsed / shake_seconds)
                instance.progress = progress
                remaining = max(0, shake_seconds - elapsed)
                instance.estimated_remaining_time = timedelta(seconds=remaining)

            logger.info("Shake completed (simulation)")
        else:
            timeout = COMMAND_TIMEOUTS["SHA"] + (Time / 100.0)
            self._send_command(f"SHA {Time} {Distance} {Speed}", timeout=timeout)
            logger.info("Shake completed (real)")

        self._push_device_status("Shake completed")
        return Shake_Responses()
