# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.screenstreamer import (
    CaptureError,
    GetLatestFrame_Responses,
    ListWindows_Responses,
    ScreenStreamerBase,
    StartCapture_Responses,
    StopCapture_Responses,
    WindowNotFound,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)


def _make_placeholder_jpeg() -> bytes:
    """Generate a 320x240 placeholder JPEG with text for simulation mode."""
    import io
    from PIL import Image, ImageDraw

    img = Image.new('RGB', (320, 240), color=(40, 40, 40))
    draw = ImageDraw.Draw(img)
    draw.text((60, 100), "SIMULATION MODE", fill=(200, 200, 200))
    draw.text((80, 130), "Screen Streamer", fill=(140, 140, 140))
    buf = io.BytesIO()
    img.save(buf, format='JPEG', quality=70)
    return buf.getvalue()


class ScreenStreamerImpl(ScreenStreamerBase):
    """Screen streaming feature using Win32 window capture.

    In simulation mode, returns a placeholder JPEG.
    In real mode, captures the VENUS Run Control window using PrintWindow/BitBlt.
    """

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._simulation_mode: bool = True
        self._sim_capturing: bool = False
        self._capture = None  # Lazy import of ScreenCapture

    def _get_capture(self):
        """Lazy-load the ScreenCapture to avoid Win32 import errors on non-Windows."""
        if self._capture is None:
            from ..win32_capture import ScreenCapture
            self._capture = ScreenCapture()
        return self._capture

    def get_IsCapturing(self, *, metadata: MetadataDict) -> bool:
        if self._simulation_mode:
            return self._sim_capturing
        return self._get_capture().is_capturing

    def ListWindows(self, *, metadata: MetadataDict) -> ListWindows_Responses:
        logger.info("ListWindows: simulation=%s", self._simulation_mode)

        if self._simulation_mode:
            return ListWindows_Responses(WindowTitles=[
                "Simulated Window 1",
                "Simulated Window 2",
                "VENUS Run Control (simulated)",
            ])

        try:
            from ..win32_capture import list_all_windows
            titles = list_all_windows()
            return ListWindows_Responses(WindowTitles=titles)
        except ImportError:
            raise CaptureError("pywin32 not installed on server")
        except Exception as e:
            raise CaptureError(str(e))

    def StartCapture(self, WindowTitle: str, *, metadata: MetadataDict) -> StartCapture_Responses:
        logger.info("StartCapture: window='%s', simulation=%s", WindowTitle, self._simulation_mode)

        if self._simulation_mode:
            self._sim_capturing = True
            return StartCapture_Responses()

        try:
            self._get_capture().start(WindowTitle)
        except RuntimeError as e:
            if "No window found" in str(e):
                raise WindowNotFound(str(e))
            raise CaptureError(str(e))
        except Exception as e:
            raise CaptureError(str(e))
        return StartCapture_Responses()

    def StopCapture(self, *, metadata: MetadataDict) -> StopCapture_Responses:
        logger.info("StopCapture")

        if self._simulation_mode:
            self._sim_capturing = False
            return StopCapture_Responses()

        self._get_capture().stop()
        return StopCapture_Responses()

    def GetLatestFrame(self, *, metadata: MetadataDict) -> GetLatestFrame_Responses:
        if self._simulation_mode:
            if not self._sim_capturing:
                raise CaptureError("Not capturing. Call StartCapture first.")
            return GetLatestFrame_Responses(Frame=_make_placeholder_jpeg())

        capture = self._get_capture()
        frame = capture.latest_frame
        if frame is None:
            raise CaptureError("No frame available. Ensure capture is running and the window is visible.")
        return GetLatestFrame_Responses(Frame=frame)
