# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.simulationcontroller import (
    SimulationControllerBase,
    StartSimulationMode_Responses,
    StopSimulationMode_Responses,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)


class SimulationControllerImpl(SimulationControllerBase):
    """Controls simulation mode for the server.

    When simulation mode is active, the temperature controller uses faster
    ramp rates and simulated sensor noise. When off, it behaves as if
    connected to real hardware (which doesn't exist in this learning project,
    so the behavior is slightly different to illustrate the concept).
    """

    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self._simulation_mode: bool = True  # Start in simulation mode by default

    def start(self) -> None:
        super().start()
        # Push the initial simulation mode value to subscribers
        self.update_SimulationMode(self._simulation_mode)
        logger.info("SimulationController started (simulation_mode=%s)", self._simulation_mode)

    @property
    def simulation_mode(self) -> bool:
        return self._simulation_mode

    def StartSimulationMode(self, *, metadata: MetadataDict) -> StartSimulationMode_Responses:
        logger.info("Entering simulation mode")
        self._simulation_mode = True
        self.update_SimulationMode(True)
        # Notify the temperature controller about the mode change
        self.parent_server.temperaturecontroller._simulation_mode = True
        self.parent_server.screenstreamer._simulation_mode = True
        self.parent_server.messagingclient._simulation_mode = True
        return StartSimulationMode_Responses()

    def StopSimulationMode(self, *, metadata: MetadataDict) -> StopSimulationMode_Responses:
        logger.info("Exiting simulation mode (entering real mode)")
        self._simulation_mode = False
        self.update_SimulationMode(False)
        # Notify the temperature controller about the mode change
        self.parent_server.temperaturecontroller._simulation_mode = False
        self.parent_server.screenstreamer._simulation_mode = False
        self.parent_server.messagingclient._simulation_mode = False
        return StopSimulationMode_Responses()
