# Generated by sila2.code_generator; sila2.__version__: 0.14.0
# Implementation by learning project
from __future__ import annotations

import logging
import math
import random
import threading
import time
from datetime import timedelta
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.temperaturecontroller import (
    GetDeviceStatus_Responses,
    HeaterFault,
    OverTemperature,
    SetTemperature_IntermediateResponses,
    SetTemperature_Responses,
    StopTemperatureControl_Responses,
    TemperatureControllerBase,
)

if TYPE_CHECKING:
    from ..server import Server

logger = logging.getLogger(__name__)

# Simulated physical constants
AMBIENT_TEMPERATURE = 22.0  # Room temperature in degC
DRIFT_RATE = 0.1  # How fast temp drifts toward ambient (degC/s) when not controlling
MAX_SAFE_TEMPERATURE = 200.0
MIN_SAFE_TEMPERATURE = -20.0


class TemperatureControllerImpl(TemperatureControllerBase):
    """Simulated temperature controller implementation.

    Maintains internal state for a virtual heating/cooling device that:
    - Ramps to a target temperature at a configurable rate
    - Drifts toward ambient when idle
    - Reports current temperature via an observable property
    - Can raise OverTemperature and HeaterFault errors for learning
    """

    def __init__(self, parent_server: Server, simulation_mode: bool = True) -> None:
        super().__init__(parent_server=parent_server)

        self.SetTemperature_default_lifetime_of_execution = timedelta(minutes=30)

        # Internal device state
        self._current_temp: float = AMBIENT_TEMPERATURE
        self._target_temp: float = float("nan")
        self._is_controlling: bool = False
        self._simulation_mode: bool = simulation_mode
        self._fault_active: bool = False
        self._stop_event = threading.Event()
        self._state_lock = threading.Lock()

        # For triggering faults deliberately (learning/testing)
        self._inject_fault: bool = False

    def start(self) -> None:
        """Called when the server starts. Begin the background temperature simulation."""
        super().start()
        logger.info(
            "TemperatureController started (simulation=%s, ambient=%.1f degC)",
            self._simulation_mode,
            AMBIENT_TEMPERATURE,
        )
        # Push the initial temperature to any subscribers
        self.update_CurrentTemperature(self._current_temp)

        # Background thread to drift temperature toward ambient when idle
        # and to push periodic observable property updates
        self._stop_event.clear()

        def background_update():
            while not self._stop_event.wait(timeout=1.0):
                with self._state_lock:
                    if not self._is_controlling:
                        # Drift toward ambient
                        diff = AMBIENT_TEMPERATURE - self._current_temp
                        if abs(diff) > 0.01:
                            step = min(abs(diff), DRIFT_RATE)
                            self._current_temp += step if diff > 0 else -step
                self.update_CurrentTemperature(self._current_temp)

        self._bg_thread = threading.Thread(target=background_update, daemon=True)
        self._bg_thread.start()

    def stop(self) -> None:
        """Called when the server stops. Clean up background threads."""
        self._stop_event.set()
        if hasattr(self, "_bg_thread"):
            self._bg_thread.join(timeout=5.0)
        logger.info("TemperatureController stopped")
        super().stop()

    # ----------------------------------------------------------------
    # Properties
    # ----------------------------------------------------------------

    def get_TargetTemperature(self, *, metadata: MetadataDict) -> float:
        return self._target_temp

    def get_IsControlling(self, *, metadata: MetadataDict) -> bool:
        return self._is_controlling

    # CurrentTemperature is observable -- updates are pushed via
    # self.update_CurrentTemperature() in the background thread and
    # during SetTemperature ramp.

    # ----------------------------------------------------------------
    # Unobservable Commands
    # ----------------------------------------------------------------

    def StopTemperatureControl(self, *, metadata: MetadataDict) -> StopTemperatureControl_Responses:
        with self._state_lock:
            self._is_controlling = False
            self._target_temp = float("nan")
            temp_at_stop = self._current_temp
        logger.info("Temperature control stopped at %.1f degC", temp_at_stop)
        return StopTemperatureControl_Responses(TemperatureAtStop=temp_at_stop)

    def GetDeviceStatus(self, *, metadata: MetadataDict) -> GetDeviceStatus_Responses:
        with self._state_lock:
            mode = "SIMULATION" if self._simulation_mode else "REAL"
            if self._fault_active:
                msg = f"[{mode}] FAULT: Heater fault active. Last reading: {self._current_temp:.1f} degC"
            elif self._is_controlling:
                msg = f"[{mode}] Ramping to {self._target_temp:.1f} degC (currently {self._current_temp:.1f} degC)"
            else:
                msg = f"[{mode}] Idle at {self._current_temp:.1f} degC"
        return GetDeviceStatus_Responses(StatusMessage=msg)

    # ----------------------------------------------------------------
    # Observable Command: SetTemperature
    # ----------------------------------------------------------------

    def SetTemperature(
        self,
        TargetTemperature: float,
        RampRate: float,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[SetTemperature_IntermediateResponses],
    ) -> SetTemperature_Responses:
        """Ramp temperature to target, reporting progress and intermediate readings."""

        logger.info("SetTemperature called: target=%.1f degC, rate=%.1f degC/s", TargetTemperature, RampRate)

        # Check for existing fault
        if self._fault_active:
            raise HeaterFault("Cannot set temperature: heater fault is active. Reset the device first.")

        # Transition from 'waiting' to 'running'
        instance.begin_execution()

        with self._state_lock:
            self._target_temp = TargetTemperature
            self._is_controlling = True

        # Calculate estimated total time
        temp_diff = abs(TargetTemperature - self._current_temp)
        estimated_seconds = temp_diff / RampRate if RampRate > 0 else 0
        instance.estimated_remaining_time = timedelta(seconds=estimated_seconds)
        instance.lifetime_of_execution = timedelta(seconds=estimated_seconds + 60)

        # Simulate the ramp in a loop
        # In simulation mode: fast updates, clean values
        # In real mode: slower updates, sensor noise, occasional jitter
        if self._simulation_mode:
            UPDATE_INTERVAL = 0.5
            noise_amplitude = 0.0  # Perfect readings in simulation
        else:
            UPDATE_INTERVAL = 1.0  # Real hardware is slower to poll
            noise_amplitude = 0.3  # Sensor noise in real mode

        direction = 1.0 if TargetTemperature > self._current_temp else -1.0
        start_temp = self._current_temp

        while True:
            # Check if we should inject a fault (for error-handling demos)
            if self._inject_fault:
                self._inject_fault = False
                with self._state_lock:
                    self._fault_active = True
                    self._is_controlling = False
                raise HeaterFault("Simulated heater fault injected for testing!")

            with self._state_lock:
                if not self._is_controlling:
                    # StopTemperatureControl was called during ramp
                    logger.info("Ramp interrupted by stop command at %.1f degC", self._current_temp)
                    return SetTemperature_Responses(FinalTemperature=self._current_temp)

                # Step the temperature
                step = RampRate * UPDATE_INTERVAL
                self._current_temp += direction * step

                # Check if we've reached or passed the target
                if direction > 0 and self._current_temp >= TargetTemperature:
                    self._current_temp = TargetTemperature
                elif direction < 0 and self._current_temp <= TargetTemperature:
                    self._current_temp = TargetTemperature

                current = self._current_temp

            # Safety check
            if current > MAX_SAFE_TEMPERATURE:
                with self._state_lock:
                    self._is_controlling = False
                    self._fault_active = True
                raise OverTemperature(
                    f"Temperature {current:.1f} degC exceeds maximum safe limit of {MAX_SAFE_TEMPERATURE} degC"
                )

            # Calculate and report progress (0.0 to 1.0, NOT 0-100)
            total_diff = abs(TargetTemperature - start_temp)
            if total_diff > 0:
                progress = min(1.0, abs(current - start_temp) / total_diff)
            else:
                progress = 1.0
            instance.progress = progress

            remaining = abs(TargetTemperature - current) / RampRate if RampRate > 0 else 0
            instance.estimated_remaining_time = timedelta(seconds=remaining)

            # Send intermediate response with current temperature
            # In real mode, add sensor noise to the reported value
            reported_temp = current + random.gauss(0, noise_amplitude) if noise_amplitude > 0 else current
            instance.send_intermediate_response(
                SetTemperature_IntermediateResponses(CurrentTemperature=reported_temp)
            )

            # Also push to observable property subscribers
            self.update_CurrentTemperature(reported_temp)

            logger.debug("Ramp progress: %.1f degC (%.0f%%)", current, progress)

            # Check if we've reached the target
            if abs(current - TargetTemperature) < 0.01:
                break

            time.sleep(UPDATE_INTERVAL)

        # Ramp complete
        with self._state_lock:
            self._is_controlling = False
            final = self._current_temp

        logger.info("SetTemperature complete: final=%.1f degC", final)
        return SetTemperature_Responses(FinalTemperature=final)

    # ----------------------------------------------------------------
    # Helper for fault injection (used by test clients)
    # ----------------------------------------------------------------

    def trigger_fault(self) -> None:
        """Set a flag to inject a HeaterFault on the next ramp cycle.
        Useful for learning about error handling."""
        self._inject_fault = True
        logger.warning("Fault injection armed -- will fire on next SetTemperature ramp cycle")

    def reset_fault(self) -> None:
        """Clear an active heater fault so the device can be used again."""
        with self._state_lock:
            self._fault_active = False
            self._inject_fault = False
        logger.info("Fault cleared")
