# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.lockcontroller_impl import LockControllerImpl
from .feature_implementations.messagingclient_impl import MessagingClientImpl
from .feature_implementations.pheniximager_impl import PhenixImagerImpl
from .feature_implementations.screenstreamer_impl import ScreenStreamerImpl
from .feature_implementations.simulationcontroller_impl import SimulationControllerImpl
from .generated.lockcontroller import LockControllerFeature
from .generated.messagingclient import MessagingClientFeature
from .generated.pheniximager import PhenixImagerFeature
from .generated.screenstreamer import ScreenStreamerFeature
from .generated.simulationcontroller import SimulationControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "Phenix Imager"
        if description is None:
            description = "PerkinElmer Opera Phenix high-content imager (SiLA 2)"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="PhenixImager",
            server_version="0.1",
            server_vendor_url="https://github.com/keyser",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        # Main feature
        self.pheniximager = PhenixImagerImpl(self)
        self.set_feature_implementation(PhenixImagerFeature, self.pheniximager)

        # ScreenStreamer support
        self.screenstreamer = ScreenStreamerImpl(self)
        self.set_feature_implementation(ScreenStreamerFeature, self.screenstreamer)

        # MessagingClient support
        self.messagingclient = MessagingClientImpl(self)
        self.set_feature_implementation(MessagingClientFeature, self.messagingclient)

        # SimulationController
        self.simulationcontroller = SimulationControllerImpl(self)
        self.set_feature_implementation(SimulationControllerFeature, self.simulationcontroller)

        # LockController
        self.set_feature_implementation(LockControllerFeature, LockControllerImpl(self))
